// Copyright 2026 Henry Zektser.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mcpdoll/snapshot/v1/distribution.proto

package snapshotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotDistribution_Subscribe_FullMethodName    = "/mcpdoll.snapshot.v1.SnapshotDistribution/Subscribe"
	SnapshotDistribution_Fetch_FullMethodName        = "/mcpdoll.snapshot.v1.SnapshotDistribution/Fetch"
	SnapshotDistribution_ReportStatus_FullMethodName = "/mcpdoll.snapshot.v1.SnapshotDistribution/ReportStatus"
)

// SnapshotDistributionClient is the client API for SnapshotDistribution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotDistribution streams signed snapshots to data-plane instances.
//
// The stream is the only channel from control plane to data plane. There is no
// push endpoint on the data plane and no request path that reaches back into the
// control plane during serving: a data plane whose control plane is down keeps
// serving its current snapshot indefinitely.
type SnapshotDistributionClient interface {
	// Subscribe returns the current snapshot immediately, then every subsequent
	// one as it is published. The data plane reconnects with backoff on stream
	// failure and keeps serving throughout.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEvent], error)
	// Fetch retrieves one snapshot by version. Used for local rollback and by the
	// CLI to inspect what is deployed.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*SignedSnapshot, error)
	// ReportStatus lets an instance tell the control plane what it is serving, so
	// the console can show snapshot version and age per instance and an operator
	// can see a stalled rollout.
	ReportStatus(ctx context.Context, in *InstanceStatus, opts ...grpc.CallOption) (*ReportStatusResponse, error)
}

type snapshotDistributionClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotDistributionClient(cc grpc.ClientConnInterface) SnapshotDistributionClient {
	return &snapshotDistributionClient{cc}
}

func (c *snapshotDistributionClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnapshotDistribution_ServiceDesc.Streams[0], SnapshotDistribution_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SnapshotEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotDistribution_SubscribeClient = grpc.ServerStreamingClient[SnapshotEvent]

func (c *snapshotDistributionClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*SignedSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedSnapshot)
	err := c.cc.Invoke(ctx, SnapshotDistribution_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotDistributionClient) ReportStatus(ctx context.Context, in *InstanceStatus, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, SnapshotDistribution_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotDistributionServer is the server API for SnapshotDistribution service.
// All implementations must embed UnimplementedSnapshotDistributionServer
// for forward compatibility.
//
// SnapshotDistribution streams signed snapshots to data-plane instances.
//
// The stream is the only channel from control plane to data plane. There is no
// push endpoint on the data plane and no request path that reaches back into the
// control plane during serving: a data plane whose control plane is down keeps
// serving its current snapshot indefinitely.
type SnapshotDistributionServer interface {
	// Subscribe returns the current snapshot immediately, then every subsequent
	// one as it is published. The data plane reconnects with backoff on stream
	// failure and keeps serving throughout.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SnapshotEvent]) error
	// Fetch retrieves one snapshot by version. Used for local rollback and by the
	// CLI to inspect what is deployed.
	Fetch(context.Context, *FetchRequest) (*SignedSnapshot, error)
	// ReportStatus lets an instance tell the control plane what it is serving, so
	// the console can show snapshot version and age per instance and an operator
	// can see a stalled rollout.
	ReportStatus(context.Context, *InstanceStatus) (*ReportStatusResponse, error)
	mustEmbedUnimplementedSnapshotDistributionServer()
}

// UnimplementedSnapshotDistributionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotDistributionServer struct{}

func (UnimplementedSnapshotDistributionServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SnapshotEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSnapshotDistributionServer) Fetch(context.Context, *FetchRequest) (*SignedSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedSnapshotDistributionServer) ReportStatus(context.Context, *InstanceStatus) (*ReportStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedSnapshotDistributionServer) mustEmbedUnimplementedSnapshotDistributionServer() {}
func (UnimplementedSnapshotDistributionServer) testEmbeddedByValue()                              {}

// UnsafeSnapshotDistributionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotDistributionServer will
// result in compilation errors.
type UnsafeSnapshotDistributionServer interface {
	mustEmbedUnimplementedSnapshotDistributionServer()
}

func RegisterSnapshotDistributionServer(s grpc.ServiceRegistrar, srv SnapshotDistributionServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotDistributionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotDistribution_ServiceDesc, srv)
}

func _SnapshotDistribution_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapshotDistributionServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SnapshotEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotDistribution_SubscribeServer = grpc.ServerStreamingServer[SnapshotEvent]

func _SnapshotDistribution_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotDistributionServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotDistribution_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotDistributionServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotDistribution_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotDistributionServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotDistribution_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotDistributionServer).ReportStatus(ctx, req.(*InstanceStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotDistribution_ServiceDesc is the grpc.ServiceDesc for SnapshotDistribution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotDistribution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcpdoll.snapshot.v1.SnapshotDistribution",
	HandlerType: (*SnapshotDistributionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _SnapshotDistribution_Fetch_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _SnapshotDistribution_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SnapshotDistribution_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcpdoll/snapshot/v1/distribution.proto",
}
