// Copyright 2026 The MCPDoll Authors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: mcpdoll/snapshot/v1/distribution.proto

package snapshotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Version the instance already has. The server sends the current snapshot
	// only if it is newer, so a reconnect does not force a redundant swap.
	KnownVersion  int64  `protobuf:"varint,2,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	InstanceId    string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SubscribeRequest) GetKnownVersion() int64 {
	if x != nil {
		return x.KnownVersion
	}
	return 0
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type SnapshotEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SnapshotEvent_Snapshot
	//	*SnapshotEvent_Heartbeat
	//	*SnapshotEvent_Rollback
	Event         isSnapshotEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEvent) Reset() {
	*x = SnapshotEvent{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEvent) ProtoMessage() {}

func (x *SnapshotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEvent.ProtoReflect.Descriptor instead.
func (*SnapshotEvent) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotEvent) GetEvent() isSnapshotEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SnapshotEvent) GetSnapshot() *SignedSnapshot {
	if x != nil {
		if x, ok := x.Event.(*SnapshotEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *SnapshotEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*SnapshotEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SnapshotEvent) GetRollback() *RollbackDirective {
	if x != nil {
		if x, ok := x.Event.(*SnapshotEvent_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

type isSnapshotEvent_Event interface {
	isSnapshotEvent_Event()
}

type SnapshotEvent_Snapshot struct {
	Snapshot *SignedSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type SnapshotEvent_Heartbeat struct {
	// Sent when the subscriber is already current, so the stream is
	// demonstrably alive rather than merely idle.
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type SnapshotEvent_Rollback struct {
	// Sent when the control plane wants instances to fall back to an earlier
	// version — an operator-initiated rollback.
	Rollback *RollbackDirective `protobuf:"bytes,3,opt,name=rollback,proto3,oneof"`
}

func (*SnapshotEvent_Snapshot) isSnapshotEvent_Event() {}

func (*SnapshotEvent_Heartbeat) isSnapshotEvent_Event() {}

func (*SnapshotEvent_Rollback) isSnapshotEvent_Event() {}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	At             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Heartbeat) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type RollbackDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVersion int64                  `protobuf:"varint,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	OrderedBy     string                 `protobuf:"bytes,3,opt,name=ordered_by,json=orderedBy,proto3" json:"ordered_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDirective) Reset() {
	*x = RollbackDirective{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDirective) ProtoMessage() {}

func (x *RollbackDirective) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDirective.ProtoReflect.Descriptor instead.
func (*RollbackDirective) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackDirective) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *RollbackDirective) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RollbackDirective) GetOrderedBy() string {
	if x != nil {
		return x.OrderedBy
	}
	return ""
}

type FetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Zero means "the current snapshot".
	Version       int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{4}
}

func (x *FetchRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *FetchRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type InstanceStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ServingVersion int64                  `protobuf:"varint,3,opt,name=serving_version,json=servingVersion,proto3" json:"serving_version,omitempty"`
	ServingSince   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=serving_since,json=servingSince,proto3" json:"serving_since,omitempty"`
	// Set when the instance rejected the most recent snapshot, with the reason,
	// so a signature or validation failure surfaces in the console rather than
	// only in one instance's logs.
	LastRejectReason  string `protobuf:"bytes,5,opt,name=last_reject_reason,json=lastRejectReason,proto3" json:"last_reject_reason,omitempty"`
	LastRejectVersion int64  `protobuf:"varint,6,opt,name=last_reject_version,json=lastRejectVersion,proto3" json:"last_reject_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{5}
}

func (x *InstanceStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceStatus) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *InstanceStatus) GetServingVersion() int64 {
	if x != nil {
		return x.ServingVersion
	}
	return 0
}

func (x *InstanceStatus) GetServingSince() *timestamppb.Timestamp {
	if x != nil {
		return x.ServingSince
	}
	return nil
}

func (x *InstanceStatus) GetLastRejectReason() string {
	if x != nil {
		return x.LastRejectReason
	}
	return ""
}

func (x *InstanceStatus) GetLastRejectVersion() int64 {
	if x != nil {
		return x.LastRejectVersion
	}
	return 0
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP(), []int{6}
}

var File_mcpdoll_snapshot_v1_distribution_proto protoreflect.FileDescriptor

const file_mcpdoll_snapshot_v1_distribution_proto_rawDesc = "" +
	"\n" +
	"&mcpdoll/snapshot/v1/distribution.proto\x12\x13mcpdoll.snapshot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"mcpdoll/snapshot/v1/snapshot.proto\"o\n" +
	"\x10SubscribeRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12#\n" +
	"\rknown_version\x18\x02 \x01(\x03R\fknownVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"\xe1\x01\n" +
	"\rSnapshotEvent\x12A\n" +
	"\bsnapshot\x18\x01 \x01(\v2#.mcpdoll.snapshot.v1.SignedSnapshotH\x00R\bsnapshot\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1e.mcpdoll.snapshot.v1.HeartbeatH\x00R\theartbeat\x12D\n" +
	"\brollback\x18\x03 \x01(\v2&.mcpdoll.snapshot.v1.RollbackDirectiveH\x00R\brollbackB\a\n" +
	"\x05event\"`\n" +
	"\tHeartbeat\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\"q\n" +
	"\x11RollbackDirective\x12%\n" +
	"\x0etarget_version\x18\x01 \x01(\x03R\rtargetVersion\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"ordered_by\x18\x03 \x01(\tR\torderedBy\"?\n" +
	"\fFetchRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x90\x02\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12'\n" +
	"\x0fserving_version\x18\x03 \x01(\x03R\x0eservingVersion\x12?\n" +
	"\rserving_since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fservingSince\x12,\n" +
	"\x12last_reject_reason\x18\x05 \x01(\tR\x10lastRejectReason\x12.\n" +
	"\x13last_reject_version\x18\x06 \x01(\x03R\x11lastRejectVersion\"\x16\n" +
	"\x14ReportStatusResponse2\xa1\x02\n" +
	"\x14SnapshotDistribution\x12X\n" +
	"\tSubscribe\x12%.mcpdoll.snapshot.v1.SubscribeRequest\x1a\".mcpdoll.snapshot.v1.SnapshotEvent0\x01\x12O\n" +
	"\x05Fetch\x12!.mcpdoll.snapshot.v1.FetchRequest\x1a#.mcpdoll.snapshot.v1.SignedSnapshot\x12^\n" +
	"\fReportStatus\x12#.mcpdoll.snapshot.v1.InstanceStatus\x1a).mcpdoll.snapshot.v1.ReportStatusResponseB6Z4github.com/mcpdoll/mcpdoll/internal/proto/snapshotpbb\x06proto3"

var (
	file_mcpdoll_snapshot_v1_distribution_proto_rawDescOnce sync.Once
	file_mcpdoll_snapshot_v1_distribution_proto_rawDescData []byte
)

func file_mcpdoll_snapshot_v1_distribution_proto_rawDescGZIP() []byte {
	file_mcpdoll_snapshot_v1_distribution_proto_rawDescOnce.Do(func() {
		file_mcpdoll_snapshot_v1_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpdoll_snapshot_v1_distribution_proto_rawDesc), len(file_mcpdoll_snapshot_v1_distribution_proto_rawDesc)))
	})
	return file_mcpdoll_snapshot_v1_distribution_proto_rawDescData
}

var file_mcpdoll_snapshot_v1_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mcpdoll_snapshot_v1_distribution_proto_goTypes = []any{
	(*SubscribeRequest)(nil),      // 0: mcpdoll.snapshot.v1.SubscribeRequest
	(*SnapshotEvent)(nil),         // 1: mcpdoll.snapshot.v1.SnapshotEvent
	(*Heartbeat)(nil),             // 2: mcpdoll.snapshot.v1.Heartbeat
	(*RollbackDirective)(nil),     // 3: mcpdoll.snapshot.v1.RollbackDirective
	(*FetchRequest)(nil),          // 4: mcpdoll.snapshot.v1.FetchRequest
	(*InstanceStatus)(nil),        // 5: mcpdoll.snapshot.v1.InstanceStatus
	(*ReportStatusResponse)(nil),  // 6: mcpdoll.snapshot.v1.ReportStatusResponse
	(*SignedSnapshot)(nil),        // 7: mcpdoll.snapshot.v1.SignedSnapshot
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_mcpdoll_snapshot_v1_distribution_proto_depIdxs = []int32{
	7, // 0: mcpdoll.snapshot.v1.SnapshotEvent.snapshot:type_name -> mcpdoll.snapshot.v1.SignedSnapshot
	2, // 1: mcpdoll.snapshot.v1.SnapshotEvent.heartbeat:type_name -> mcpdoll.snapshot.v1.Heartbeat
	3, // 2: mcpdoll.snapshot.v1.SnapshotEvent.rollback:type_name -> mcpdoll.snapshot.v1.RollbackDirective
	8, // 3: mcpdoll.snapshot.v1.Heartbeat.at:type_name -> google.protobuf.Timestamp
	8, // 4: mcpdoll.snapshot.v1.InstanceStatus.serving_since:type_name -> google.protobuf.Timestamp
	0, // 5: mcpdoll.snapshot.v1.SnapshotDistribution.Subscribe:input_type -> mcpdoll.snapshot.v1.SubscribeRequest
	4, // 6: mcpdoll.snapshot.v1.SnapshotDistribution.Fetch:input_type -> mcpdoll.snapshot.v1.FetchRequest
	5, // 7: mcpdoll.snapshot.v1.SnapshotDistribution.ReportStatus:input_type -> mcpdoll.snapshot.v1.InstanceStatus
	1, // 8: mcpdoll.snapshot.v1.SnapshotDistribution.Subscribe:output_type -> mcpdoll.snapshot.v1.SnapshotEvent
	7, // 9: mcpdoll.snapshot.v1.SnapshotDistribution.Fetch:output_type -> mcpdoll.snapshot.v1.SignedSnapshot
	6, // 10: mcpdoll.snapshot.v1.SnapshotDistribution.ReportStatus:output_type -> mcpdoll.snapshot.v1.ReportStatusResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mcpdoll_snapshot_v1_distribution_proto_init() }
func file_mcpdoll_snapshot_v1_distribution_proto_init() {
	if File_mcpdoll_snapshot_v1_distribution_proto != nil {
		return
	}
	file_mcpdoll_snapshot_v1_snapshot_proto_init()
	file_mcpdoll_snapshot_v1_distribution_proto_msgTypes[1].OneofWrappers = []any{
		(*SnapshotEvent_Snapshot)(nil),
		(*SnapshotEvent_Heartbeat)(nil),
		(*SnapshotEvent_Rollback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpdoll_snapshot_v1_distribution_proto_rawDesc), len(file_mcpdoll_snapshot_v1_distribution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcpdoll_snapshot_v1_distribution_proto_goTypes,
		DependencyIndexes: file_mcpdoll_snapshot_v1_distribution_proto_depIdxs,
		MessageInfos:      file_mcpdoll_snapshot_v1_distribution_proto_msgTypes,
	}.Build()
	File_mcpdoll_snapshot_v1_distribution_proto = out.File
	file_mcpdoll_snapshot_v1_distribution_proto_goTypes = nil
	file_mcpdoll_snapshot_v1_distribution_proto_depIdxs = nil
}
