// Copyright 2026 Henry Zektser.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: mcpdoll/snapshot/v1/snapshot.proto

package snapshotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EffectClass describes what invoking a tool does to the world. It drives the
// guard's concurrency decision, idempotency requirements, and per-class plugin
// failure policy — so it is part of the admitted definition, not a runtime
// guess.
type EffectClass int32

const (
	EffectClass_EFFECT_CLASS_UNSPECIFIED EffectClass = 0
	// No observable side effect. Safe to run speculatively in parallel with a
	// guard check, and safe to retry.
	EffectClass_EFFECT_CLASS_READ EffectClass = 1
	// Creates or modifies state. Requires an idempotency key; the guard must
	// clear it before dispatch, not alongside.
	EffectClass_EFFECT_CLASS_WRITE EffectClass = 2
	// Irreversible. Same as write, plus stricter default policy.
	EffectClass_EFFECT_CLASS_DESTRUCTIVE EffectClass = 3
)

// Enum value maps for EffectClass.
var (
	EffectClass_name = map[int32]string{
		0: "EFFECT_CLASS_UNSPECIFIED",
		1: "EFFECT_CLASS_READ",
		2: "EFFECT_CLASS_WRITE",
		3: "EFFECT_CLASS_DESTRUCTIVE",
	}
	EffectClass_value = map[string]int32{
		"EFFECT_CLASS_UNSPECIFIED": 0,
		"EFFECT_CLASS_READ":        1,
		"EFFECT_CLASS_WRITE":       2,
		"EFFECT_CLASS_DESTRUCTIVE": 3,
	}
)

func (x EffectClass) Enum() *EffectClass {
	p := new(EffectClass)
	*p = x
	return p
}

func (x EffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (EffectClass) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[0]
}

func (x EffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectClass.Descriptor instead.
func (EffectClass) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

// ServingMode controls what the gateway does when a backend's live tool list
// disagrees with what was admitted.
type ServingMode int32

const (
	ServingMode_SERVING_MODE_UNSPECIFIED ServingMode = 0
	// Serve only admitted definitions; any divergence is drift, and the
	// divergent definition is never served.
	ServingMode_SERVING_MODE_STRICT ServingMode = 1
	// Serve admitted definitions and record the divergence, without quarantine.
	// For backends still stabilising their catalog.
	ServingMode_SERVING_MODE_ADVISORY ServingMode = 2
)

// Enum value maps for ServingMode.
var (
	ServingMode_name = map[int32]string{
		0: "SERVING_MODE_UNSPECIFIED",
		1: "SERVING_MODE_STRICT",
		2: "SERVING_MODE_ADVISORY",
	}
	ServingMode_value = map[string]int32{
		"SERVING_MODE_UNSPECIFIED": 0,
		"SERVING_MODE_STRICT":      1,
		"SERVING_MODE_ADVISORY":    2,
	}
)

func (x ServingMode) Enum() *ServingMode {
	p := new(ServingMode)
	*p = x
	return p
}

func (x ServingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[1].Descriptor()
}

func (ServingMode) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[1]
}

func (x ServingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingMode.Descriptor instead.
func (ServingMode) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

type PolicyDecision int32

const (
	PolicyDecision_POLICY_DECISION_UNSPECIFIED PolicyDecision = 0
	PolicyDecision_POLICY_DECISION_ALLOW       PolicyDecision = 1
	PolicyDecision_POLICY_DECISION_DENY        PolicyDecision = 2
	// Hide from the catalog without failing an explicit call differently from a
	// deny — used for tools a principal should not know exist.
	PolicyDecision_POLICY_DECISION_HIDE PolicyDecision = 3
	// Require human confirmation via MRTR before dispatch.
	PolicyDecision_POLICY_DECISION_CONFIRM PolicyDecision = 4
)

// Enum value maps for PolicyDecision.
var (
	PolicyDecision_name = map[int32]string{
		0: "POLICY_DECISION_UNSPECIFIED",
		1: "POLICY_DECISION_ALLOW",
		2: "POLICY_DECISION_DENY",
		3: "POLICY_DECISION_HIDE",
		4: "POLICY_DECISION_CONFIRM",
	}
	PolicyDecision_value = map[string]int32{
		"POLICY_DECISION_UNSPECIFIED": 0,
		"POLICY_DECISION_ALLOW":       1,
		"POLICY_DECISION_DENY":        2,
		"POLICY_DECISION_HIDE":        3,
		"POLICY_DECISION_CONFIRM":     4,
	}
)

func (x PolicyDecision) Enum() *PolicyDecision {
	p := new(PolicyDecision)
	*p = x
	return p
}

func (x PolicyDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[2].Descriptor()
}

func (PolicyDecision) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[2]
}

func (x PolicyDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyDecision.Descriptor instead.
func (PolicyDecision) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

// Hook is the fixed set of pipeline extension points. Seven, deliberately:
// see docs/adr/0007-seven-hooks.md.
type Hook int32

const (
	Hook_HOOK_UNSPECIFIED    Hook = 0
	Hook_HOOK_ON_REQUEST     Hook = 1
	Hook_HOOK_ON_IDENTITY    Hook = 2
	Hook_HOOK_ON_CATALOG     Hook = 3
	Hook_HOOK_ON_TOOL_CALL   Hook = 4
	Hook_HOOK_ON_TOOL_RESULT Hook = 5
	Hook_HOOK_ON_RESPONSE    Hook = 6
	Hook_HOOK_ON_AUDIT       Hook = 7
)

// Enum value maps for Hook.
var (
	Hook_name = map[int32]string{
		0: "HOOK_UNSPECIFIED",
		1: "HOOK_ON_REQUEST",
		2: "HOOK_ON_IDENTITY",
		3: "HOOK_ON_CATALOG",
		4: "HOOK_ON_TOOL_CALL",
		5: "HOOK_ON_TOOL_RESULT",
		6: "HOOK_ON_RESPONSE",
		7: "HOOK_ON_AUDIT",
	}
	Hook_value = map[string]int32{
		"HOOK_UNSPECIFIED":    0,
		"HOOK_ON_REQUEST":     1,
		"HOOK_ON_IDENTITY":    2,
		"HOOK_ON_CATALOG":     3,
		"HOOK_ON_TOOL_CALL":   4,
		"HOOK_ON_TOOL_RESULT": 5,
		"HOOK_ON_RESPONSE":    6,
		"HOOK_ON_AUDIT":       7,
	}
)

func (x Hook) Enum() *Hook {
	p := new(Hook)
	*p = x
	return p
}

func (x Hook) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[3].Descriptor()
}

func (Hook) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[3]
}

func (x Hook) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook.Descriptor instead.
func (Hook) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

type PluginRuntime int32

const (
	PluginRuntime_PLUGIN_RUNTIME_UNSPECIFIED PluginRuntime = 0
	// WebAssembly, executed in-process under a fuel limit. The default: no
	// network, no filesystem, bounded CPU.
	PluginRuntime_PLUGIN_RUNTIME_WASM PluginRuntime = 1
	// Out-of-process gRPC, for plugins that must reach the network (the LLM
	// guard) or carry a runtime the WASM host cannot host.
	PluginRuntime_PLUGIN_RUNTIME_GRPC PluginRuntime = 2
)

// Enum value maps for PluginRuntime.
var (
	PluginRuntime_name = map[int32]string{
		0: "PLUGIN_RUNTIME_UNSPECIFIED",
		1: "PLUGIN_RUNTIME_WASM",
		2: "PLUGIN_RUNTIME_GRPC",
	}
	PluginRuntime_value = map[string]int32{
		"PLUGIN_RUNTIME_UNSPECIFIED": 0,
		"PLUGIN_RUNTIME_WASM":        1,
		"PLUGIN_RUNTIME_GRPC":        2,
	}
)

func (x PluginRuntime) Enum() *PluginRuntime {
	p := new(PluginRuntime)
	*p = x
	return p
}

func (x PluginRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[4].Descriptor()
}

func (PluginRuntime) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[4]
}

func (x PluginRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginRuntime.Descriptor instead.
func (PluginRuntime) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

type RolloutState int32

const (
	RolloutState_ROLLOUT_STATE_UNSPECIFIED RolloutState = 0
	// Runs, records its verdict, and is never acted on. Every plugin starts here.
	RolloutState_ROLLOUT_STATE_SHADOW RolloutState = 1
	// Enforced for a percentage of requests, recorded for the rest.
	RolloutState_ROLLOUT_STATE_CANARY RolloutState = 2
	// Enforced for every request.
	RolloutState_ROLLOUT_STATE_ENFORCE RolloutState = 3
)

// Enum value maps for RolloutState.
var (
	RolloutState_name = map[int32]string{
		0: "ROLLOUT_STATE_UNSPECIFIED",
		1: "ROLLOUT_STATE_SHADOW",
		2: "ROLLOUT_STATE_CANARY",
		3: "ROLLOUT_STATE_ENFORCE",
	}
	RolloutState_value = map[string]int32{
		"ROLLOUT_STATE_UNSPECIFIED": 0,
		"ROLLOUT_STATE_SHADOW":      1,
		"ROLLOUT_STATE_CANARY":      2,
		"ROLLOUT_STATE_ENFORCE":     3,
	}
)

func (x RolloutState) Enum() *RolloutState {
	p := new(RolloutState)
	*p = x
	return p
}

func (x RolloutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutState) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[5].Descriptor()
}

func (RolloutState) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[5]
}

func (x RolloutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutState.Descriptor instead.
func (RolloutState) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

// FailureMode is what the pipeline does when a plugin errors, times out, or is
// skipped by an open circuit.
type FailureMode int32

const (
	FailureMode_FAILURE_MODE_UNSPECIFIED FailureMode = 0
	// Continue without the plugin's verdict. Appropriate for an enrichment
	// plugin, and for anything on a read path where availability outranks the
	// check.
	FailureMode_FAILURE_MODE_OPEN FailureMode = 1
	// Deny the request. Appropriate for an authorization plugin on a
	// destructive tool, where a missing check is not a safe default.
	FailureMode_FAILURE_MODE_CLOSED FailureMode = 2
)

// Enum value maps for FailureMode.
var (
	FailureMode_name = map[int32]string{
		0: "FAILURE_MODE_UNSPECIFIED",
		1: "FAILURE_MODE_OPEN",
		2: "FAILURE_MODE_CLOSED",
	}
	FailureMode_value = map[string]int32{
		"FAILURE_MODE_UNSPECIFIED": 0,
		"FAILURE_MODE_OPEN":        1,
		"FAILURE_MODE_CLOSED":      2,
	}
)

func (x FailureMode) Enum() *FailureMode {
	p := new(FailureMode)
	*p = x
	return p
}

func (x FailureMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[6].Descriptor()
}

func (FailureMode) Type() protoreflect.EnumType {
	return &file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes[6]
}

func (x FailureMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureMode.Descriptor instead.
func (FailureMode) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

// SignedSnapshot is the artifact the control plane publishes and the data plane
// verifies before it will serve anything from it.
//
// `snapshot_bytes` holds a serialized Snapshot, and the signature covers those
// exact octets. The data plane verifies the bytes it received and only then
// parses them; it never re-serializes a Snapshot and re-checks. That ordering
// matters: protobuf does not guarantee byte-identical serialization across
// languages or library versions, so a scheme that signed a re-serialization
// would break on a library upgrade. Signing the transmitted octets makes the
// question moot.
type SignedSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized Snapshot message.
	SnapshotBytes []byte `protobuf:"bytes,1,opt,name=snapshot_bytes,json=snapshotBytes,proto3" json:"snapshot_bytes,omitempty"`
	// Which key signed it, so a rotation can overlap rather than requiring a
	// lockstep restart of every data-plane instance.
	KeyId string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Ed25519 signature over SIGNING_CONTEXT || snapshot_bytes. The domain
	// separation prefix stops a signature minted for some other MCPDoll artifact
	// from verifying here.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Signature algorithm. Only "ed25519" is accepted today; the field exists so
	// an unknown algorithm is an explicit rejection rather than a silent
	// misinterpretation of the signature bytes.
	Algorithm     string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedSnapshot) Reset() {
	*x = SignedSnapshot{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedSnapshot) ProtoMessage() {}

func (x *SignedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedSnapshot.ProtoReflect.Descriptor instead.
func (*SignedSnapshot) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SignedSnapshot) GetSnapshotBytes() []byte {
	if x != nil {
		return x.SnapshotBytes
	}
	return nil
}

func (x *SignedSnapshot) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedSnapshot) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedSnapshot) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// SignedPrincipalSet is who exists and what they hold.
//
// Separate from the snapshot because it changes on a different clock: a
// snapshot is republished when an operator changes serving configuration and
// costs a discovery sweep of every backend, while a principal set changes
// whenever somebody is hired, a key is minted, or access is granted — and costs
// nothing (ADR 0024).
//
// Binding them together meant minting a key required re-probing every backend,
// and made a grant — which names a *scope*, deliberately independent of what
// that scope currently admits — depend on the catalog's publish cycle.
type SignedPrincipalSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized PrincipalSet message.
	SetBytes []byte `protobuf:"bytes,1,opt,name=set_bytes,json=setBytes,proto3" json:"set_bytes,omitempty"`
	KeyId    string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Ed25519 signature over PRINCIPAL_SIGNING_CONTEXT || set_bytes. Its own
	// context, so a signature minted over one artifact cannot verify against
	// another.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Algorithm     string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrincipalSet) Reset() {
	*x = SignedPrincipalSet{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrincipalSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrincipalSet) ProtoMessage() {}

func (x *SignedPrincipalSet) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrincipalSet.ProtoReflect.Descriptor instead.
func (*SignedPrincipalSet) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SignedPrincipalSet) GetSetBytes() []byte {
	if x != nil {
		return x.SetBytes
	}
	return nil
}

func (x *SignedPrincipalSet) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedPrincipalSet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPrincipalSet) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// PrincipalSet is the compiled RBAC the data plane evaluates against.
type PrincipalSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic. The data plane refuses a set no newer than the one it holds.
	Version  int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// The role catalog. Travels with the principals because a grant naming a role
	// the catalog does not define authorizes nothing — splitting them would let
	// the two arrive out of step and silently deauthorize everyone.
	RolePermissions []*RolePermission `protobuf:"bytes,3,rep,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	Principals      []*Principal      `protobuf:"bytes,4,rep,name=principals,proto3" json:"principals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrincipalSet) Reset() {
	*x = PrincipalSet{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalSet) ProtoMessage() {}

func (x *PrincipalSet) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalSet.ProtoReflect.Descriptor instead.
func (*PrincipalSet) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *PrincipalSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PrincipalSet) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *PrincipalSet) GetRolePermissions() []*RolePermission {
	if x != nil {
		return x.RolePermissions
	}
	return nil
}

func (x *PrincipalSet) GetPrincipals() []*Principal {
	if x != nil {
		return x.Principals
	}
	return nil
}

// SignedRevocationList is the second signed artifact the data plane loads.
//
// It exists because everything else in this system takes effect at snapshot
// latency, and a leaked credential is the one case where that is the wrong
// answer (ADR 0023). It can only *subtract*: a principal named here is refused
// whatever the snapshot says, and there is nothing in it that could widen
// anything. That is what keeps "why was this allowed?" answerable from the
// snapshot alone.
type SignedRevocationList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized RevocationList message.
	ListBytes []byte `protobuf:"bytes,1,opt,name=list_bytes,json=listBytes,proto3" json:"list_bytes,omitempty"`
	KeyId     string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Ed25519 signature over REVOCATION_SIGNING_CONTEXT || list_bytes.
	//
	// A *different* context from the snapshot's, and that is load-bearing:
	// without it a signature minted over one artifact would verify against the
	// other, so anyone who could get a snapshot signed could present its bytes
	// as a revocation list.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Algorithm     string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedRevocationList) Reset() {
	*x = SignedRevocationList{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedRevocationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedRevocationList) ProtoMessage() {}

func (x *SignedRevocationList) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedRevocationList.ProtoReflect.Descriptor instead.
func (*SignedRevocationList) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *SignedRevocationList) GetListBytes() []byte {
	if x != nil {
		return x.ListBytes
	}
	return nil
}

func (x *SignedRevocationList) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedRevocationList) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedRevocationList) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// RevocationList is the set of principals the data plane must refuse.
type RevocationList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic. The data plane refuses a list no newer than the one it holds,
	// for the same reason it refuses a stale snapshot.
	Version  int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Principal ids to refuse. Ids, not grants — there is no scope, no role, and
	// nothing here that could authorize anything.
	PrincipalIds []string `protobuf:"bytes,3,rep,name=principal_ids,json=principalIds,proto3" json:"principal_ids,omitempty"`
	// The snapshot version that already reflects everything pruned from this
	// list. A data plane serving something older would lose denials it still
	// needs, so it refuses the list and keeps its previous one — strictly more
	// denials, and self-correcting once the newer snapshot lands.
	PrunedThroughSnapshotVersion int64 `protobuf:"varint,4,opt,name=pruned_through_snapshot_version,json=prunedThroughSnapshotVersion,proto3" json:"pruned_through_snapshot_version,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RevocationList) Reset() {
	*x = RevocationList{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationList) ProtoMessage() {}

func (x *RevocationList) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationList.ProtoReflect.Descriptor instead.
func (*RevocationList) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *RevocationList) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RevocationList) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *RevocationList) GetPrincipalIds() []string {
	if x != nil {
		return x.PrincipalIds
	}
	return nil
}

func (x *RevocationList) GetPrunedThroughSnapshotVersion() int64 {
	if x != nil {
		return x.PrunedThroughSnapshotVersion
	}
	return 0
}

// Snapshot is the complete, self-contained serving configuration for one
// organization at one point in time.
//
// It is self-contained by design: the data plane must be able to serve
// correctly with the control plane unreachable, so a snapshot may not reference
// anything it does not carry. The snapshotter enforces that at build time.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic, gapless per organization. The data plane refuses to activate a
	// snapshot older than the one it is serving, which is what stops a replayed
	// or misrouted older snapshot from silently rolling back policy.
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Identifier of the build that produced this snapshot.
	Id      string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BuiltAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	// Digest of the registry state this was resolved from, so a snapshot can be
	// traced back to the exact admitted definitions it contains.
	RegistryDigest string       `protobuf:"bytes,5,opt,name=registry_digest,json=registryDigest,proto3" json:"registry_digest,omitempty"`
	Namespaces     []*Namespace `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Servers        []*Server    `protobuf:"bytes,7,rep,name=servers,proto3" json:"servers,omitempty"`
	// Tools are admitted per (toolset, tenant): the same vendor tool published
	// by two tenants' separately-deployed backends is two definitions with two
	// digests, and drift is measured against the tenant's own. See ADR 0017.
	Tools    []*ToolDefinition `protobuf:"bytes,8,rep,name=tools,proto3" json:"tools,omitempty"`
	Policies []*Policy         `protobuf:"bytes,11,rep,name=policies,proto3" json:"policies,omitempty"`
	Plugins  []*PluginManifest `protobuf:"bytes,12,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Catalog  *CatalogDefaults  `protobuf:"bytes,13,opt,name=catalog,proto3" json:"catalog,omitempty"`
	// Tenants this snapshot serves.
	Tenants []*Tenant `protobuf:"bytes,14,rep,name=tenants,proto3" json:"tenants,omitempty"`
	// Toolsets replace bundles: the unit an administrator grants (ADR 0016).
	Toolsets      []*Toolset `protobuf:"bytes,15,rep,name=toolsets,proto3" json:"toolsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetBuiltAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuiltAt
	}
	return nil
}

func (x *Snapshot) GetRegistryDigest() string {
	if x != nil {
		return x.RegistryDigest
	}
	return ""
}

func (x *Snapshot) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Snapshot) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Snapshot) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Snapshot) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Snapshot) GetPlugins() []*PluginManifest {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *Snapshot) GetCatalog() *CatalogDefaults {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *Snapshot) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *Snapshot) GetToolsets() []*Toolset {
	if x != nil {
		return x.Toolsets
	}
	return nil
}

// CatalogDefaults are the deployment-wide list-result settings. Per-toolset and
// per-policy values may only narrow these, never widen them.
type CatalogDefaults struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ceiling on the ttlMs the edge advertises.
	TtlMs int32 `protobuf:"varint,1,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// Shortened TTL used when a catalog is served from last-known-good because a
	// backend is unreachable, so clients re-ask sooner.
	DegradedTtlMs int32 `protobuf:"varint,2,opt,name=degraded_ttl_ms,json=degradedTtlMs,proto3" json:"degraded_ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogDefaults) Reset() {
	*x = CatalogDefaults{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogDefaults) ProtoMessage() {}

func (x *CatalogDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogDefaults.ProtoReflect.Descriptor instead.
func (*CatalogDefaults) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *CatalogDefaults) GetTtlMs() int32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *CatalogDefaults) GetDegradedTtlMs() int32 {
	if x != nil {
		return x.DegradedTtlMs
	}
	return 0
}

// Namespace binds a short prefix to an owning team.
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The prefix every tool in this namespace is exposed under, e.g. "crm".
	// Deterministically assigned at registration and immutable: changing it
	// renames every tool, which invalidates every client's prompt cache and
	// breaks any agent that hardcoded a name.
	Prefix       string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OwningTeamId string `protobuf:"bytes,4,opt,name=owning_team_id,json=owningTeamId,proto3" json:"owning_team_id,omitempty"`
	ProjectId    string `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// IdP group that owns this namespace. Publishing into it requires membership.
	OwnerIdpGroup string `protobuf:"bytes,6,opt,name=owner_idp_group,json=ownerIdpGroup,proto3" json:"owner_idp_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *Namespace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Namespace) GetOwningTeamId() string {
	if x != nil {
		return x.OwningTeamId
	}
	return ""
}

func (x *Namespace) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Namespace) GetOwnerIdpGroup() string {
	if x != nil {
		return x.OwnerIdpGroup
	}
	return ""
}

// Server is one registered MCP backend.
type Server struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NamespaceId string                 `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	VersionId   string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// Protocol version to pin for this backend, or empty to negotiate. Pinning
	// exists because a backend that silently upgrades can change result shapes
	// under a catalog we already admitted.
	PinnedProtocolVersion string      `protobuf:"bytes,6,opt,name=pinned_protocol_version,json=pinnedProtocolVersion,proto3" json:"pinned_protocol_version,omitempty"`
	ServingMode           ServingMode `protobuf:"varint,7,opt,name=serving_mode,json=servingMode,proto3,enum=mcpdoll.snapshot.v1.ServingMode" json:"serving_mode,omitempty"`
	// Operational metadata carried from the server.json `x-mcpdoll` extensions.
	Criticality        string         `protobuf:"bytes,8,opt,name=criticality,proto3" json:"criticality,omitempty"`                                         // "low" | "normal" | "high" | "critical"
	DataClassification string         `protobuf:"bytes,9,opt,name=data_classification,json=dataClassification,proto3" json:"data_classification,omitempty"` // "public" | "internal" | "confidential" | "restricted"
	ComplianceScope    []string       `protobuf:"bytes,10,rep,name=compliance_scope,json=complianceScope,proto3" json:"compliance_scope,omitempty"`         // e.g. ["sox", "pci"]
	OwningTeamId       string         `protobuf:"bytes,11,opt,name=owning_team_id,json=owningTeamId,proto3" json:"owning_team_id,omitempty"`
	ProjectId          string         `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TokenExchange      *TokenExchange `protobuf:"bytes,13,opt,name=token_exchange,json=tokenExchange,proto3" json:"token_exchange,omitempty"`
	Health             *HealthPolicy  `protobuf:"bytes,14,opt,name=health,proto3" json:"health,omitempty"`
	// Optional tool the prober may invoke as a canary, to distinguish "the
	// catalog is reachable" from "invocations actually work".
	CanaryTool string `protobuf:"bytes,15,opt,name=canary_tool,json=canaryTool,proto3" json:"canary_tool,omitempty"`
	// This backend's hosts, one entry per tenant.
	Bindings      []*Binding `protobuf:"bytes,16,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Server) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *Server) GetPinnedProtocolVersion() string {
	if x != nil {
		return x.PinnedProtocolVersion
	}
	return ""
}

func (x *Server) GetServingMode() ServingMode {
	if x != nil {
		return x.ServingMode
	}
	return ServingMode_SERVING_MODE_UNSPECIFIED
}

func (x *Server) GetCriticality() string {
	if x != nil {
		return x.Criticality
	}
	return ""
}

func (x *Server) GetDataClassification() string {
	if x != nil {
		return x.DataClassification
	}
	return ""
}

func (x *Server) GetComplianceScope() []string {
	if x != nil {
		return x.ComplianceScope
	}
	return nil
}

func (x *Server) GetOwningTeamId() string {
	if x != nil {
		return x.OwningTeamId
	}
	return ""
}

func (x *Server) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Server) GetTokenExchange() *TokenExchange {
	if x != nil {
		return x.TokenExchange
	}
	return nil
}

func (x *Server) GetHealth() *HealthPolicy {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *Server) GetCanaryTool() string {
	if x != nil {
		return x.CanaryTool
	}
	return ""
}

func (x *Server) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// TokenExchange configures how an inbound principal becomes a credential the
// backend accepts.
//
// There is deliberately no passthrough option. Forwarding the caller's token to
// a backend would make every backend a confused deputy holding a credential
// scoped far wider than the one tool it needs.
type TokenExchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC 8693 token endpoint.
	TokenEndpoint string `protobuf:"bytes,1,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	// Audience to request for this backend.
	Audience string `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	// Scopes to request.
	Scopes []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Reference to the client credential in the secret store — never the secret
	// itself, so a snapshot is safe to store and inspect.
	ClientCredentialRef string `protobuf:"bytes,4,opt,name=client_credential_ref,json=clientCredentialRef,proto3" json:"client_credential_ref,omitempty"`
	// Header the exchanged token is placed in. Defaults to "Authorization".
	Header string `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	// Claim-to-header mappings applied in addition, for backends that need
	// tenant or user context out of band.
	ClaimHeaders  map[string]string `protobuf:"bytes,6,rep,name=claim_headers,json=claimHeaders,proto3" json:"claim_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchange) Reset() {
	*x = TokenExchange{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchange) ProtoMessage() {}

func (x *TokenExchange) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchange.ProtoReflect.Descriptor instead.
func (*TokenExchange) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *TokenExchange) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

func (x *TokenExchange) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *TokenExchange) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenExchange) GetClientCredentialRef() string {
	if x != nil {
		return x.ClientCredentialRef
	}
	return ""
}

func (x *TokenExchange) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *TokenExchange) GetClaimHeaders() map[string]string {
	if x != nil {
		return x.ClaimHeaders
	}
	return nil
}

type HealthPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProbeIntervalMs int32                  `protobuf:"varint,1,opt,name=probe_interval_ms,json=probeIntervalMs,proto3" json:"probe_interval_ms,omitempty"`
	ProbeTimeoutMs  int32                  `protobuf:"varint,2,opt,name=probe_timeout_ms,json=probeTimeoutMs,proto3" json:"probe_timeout_ms,omitempty"`
	// How long a tool from an unreachable backend stays listed, failing its calls
	// fast. Removing it instead would invalidate every client's prompt cache.
	GraceWindowMs      int32 `protobuf:"varint,3,opt,name=grace_window_ms,json=graceWindowMs,proto3" json:"grace_window_ms,omitempty"`
	EjectAfterFailures int32 `protobuf:"varint,4,opt,name=eject_after_failures,json=ejectAfterFailures,proto3" json:"eject_after_failures,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthPolicy) Reset() {
	*x = HealthPolicy{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPolicy) ProtoMessage() {}

func (x *HealthPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPolicy.ProtoReflect.Descriptor instead.
func (*HealthPolicy) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *HealthPolicy) GetProbeIntervalMs() int32 {
	if x != nil {
		return x.ProbeIntervalMs
	}
	return 0
}

func (x *HealthPolicy) GetProbeTimeoutMs() int32 {
	if x != nil {
		return x.ProbeTimeoutMs
	}
	return 0
}

func (x *HealthPolicy) GetGraceWindowMs() int32 {
	if x != nil {
		return x.GraceWindowMs
	}
	return 0
}

func (x *HealthPolicy) GetEjectAfterFailures() int32 {
	if x != nil {
		return x.EjectAfterFailures
	}
	return 0
}

// ToolDefinition is an admitted tool, exactly as it will be served.
//
// The gateway serves these, never what a live backend currently reports. A
// backend that changes its catalog produces a drift event; it does not change
// what clients see until the change is admitted.
type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content address of the canonical form. This is the definition's identity.
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Digest with prose stripped, so drift can distinguish a reworded
	// description from a changed schema by comparing digests.
	SemanticDigest string `protobuf:"bytes,2,opt,name=semantic_digest,json=semanticDigest,proto3" json:"semantic_digest,omitempty"`
	ServerId       string `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NamespaceId    string `protobuf:"bytes,4,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// The tenant this definition was admitted for. Two tenants' backends running
	// different releases publish different schemas for the same tool, and each
	// tenant is served its own. See ADR 0017.
	TenantId string `protobuf:"bytes,15,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The toolset that contributed this tool, for catalog ordering and for the
	// authorization scope `t/<tenant>/ts/<toolset>/<name>`.
	ToolsetId string `protobuf:"bytes,16,opt,name=toolset_id,json=toolsetId,proto3" json:"toolset_id,omitempty"`
	// Name as the backend publishes it.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Name as clients see it: "<prefix>.<name>". Assigned at admission, never
	// computed at runtime, so a collision is a publish-time rejection rather
	// than a silent runtime rename.
	QualifiedName string `protobuf:"bytes,6,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	Title         string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description   string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema documents, canonicalized with `$defs` resolved.
	InputSchemaJson  string `protobuf:"bytes,9,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	OutputSchemaJson string `protobuf:"bytes,10,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"`
	// Tool annotations as canonical JSON.
	AnnotationsJson string      `protobuf:"bytes,11,opt,name=annotations_json,json=annotationsJson,proto3" json:"annotations_json,omitempty"`
	EffectClass     EffectClass `protobuf:"varint,12,opt,name=effect_class,json=effectClass,proto3,enum=mcpdoll.snapshot.v1.EffectClass" json:"effect_class,omitempty"`
	// Estimated tokens the serialized definition costs a model, schema included.
	// Budget enforcement uses this; the console's toolset composer displays it.
	TokenEstimate int32 `protobuf:"varint,13,opt,name=token_estimate,json=tokenEstimate,proto3" json:"token_estimate,omitempty"`
	// Whether the tool requires an idempotency key. Derived from effect class at
	// admission, stored explicitly so the runtime does not re-derive it.
	RequiresIdempotencyKey bool `protobuf:"varint,14,opt,name=requires_idempotency_key,json=requiresIdempotencyKey,proto3" json:"requires_idempotency_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *ToolDefinition) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ToolDefinition) GetSemanticDigest() string {
	if x != nil {
		return x.SemanticDigest
	}
	return ""
}

func (x *ToolDefinition) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ToolDefinition) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ToolDefinition) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ToolDefinition) GetToolsetId() string {
	if x != nil {
		return x.ToolsetId
	}
	return ""
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *ToolDefinition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolDefinition) GetOutputSchemaJson() string {
	if x != nil {
		return x.OutputSchemaJson
	}
	return ""
}

func (x *ToolDefinition) GetAnnotationsJson() string {
	if x != nil {
		return x.AnnotationsJson
	}
	return ""
}

func (x *ToolDefinition) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_CLASS_UNSPECIFIED
}

func (x *ToolDefinition) GetTokenEstimate() int32 {
	if x != nil {
		return x.TokenEstimate
	}
	return 0
}

func (x *ToolDefinition) GetRequiresIdempotencyKey() bool {
	if x != nil {
		return x.RequiresIdempotencyKey
	}
	return false
}

// Tenant is an isolation boundary. Every user, backend binding, and admitted
// tool belongs to exactly one.
type Tenant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Appears in every authorization scope as `t/<slug>`, which is why it is
	// constrained to characters that cannot change a scope's meaning.
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active" | "suspended" | "archived"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{12}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Binding is one tenant's hosts for a backend.
type Binding struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The definition source. Discovery reads it; replicas are compared against
	// it. A declared primary makes "which host is correct" a configuration
	// decision rather than a vote between two disagreeing hosts.
	Primary string `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	// Interchangeable hosts for the same tenant. A replica whose semantic digest
	// diverges from the primary leaves the routable pool and is reported — what
	// is *served* does not change, so a rolling deploy costs capacity rather
	// than churning every client's prompt cache. See ADR 0017.
	Replicas      []string `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{13}
}

func (x *Binding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Binding) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *Binding) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

// Toolset is a named, grantable group of tools.
//
// Replaces Bundle. The rename carries meaning: a bundle grouped namespaces for
// publication, whereas a toolset is what an administrator hands to a user, and
// its name appears inside every grant scope.
type Toolset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Leading component of the stable catalog ordering. Lower sorts first.
	Priority      int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	TokenBudget   int32 `protobuf:"varint,4,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	TtlMs         int32 `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toolset) Reset() {
	*x = Toolset{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toolset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolset) ProtoMessage() {}

func (x *Toolset) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolset.ProtoReflect.Descriptor instead.
func (*Toolset) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{14}
}

func (x *Toolset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Toolset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Toolset) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Toolset) GetTokenBudget() int32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *Toolset) GetTtlMs() int32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

// RolePermission is a Casbin `p` policy.
type RolePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermission) Reset() {
	*x = RolePermission{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermission) ProtoMessage() {}

func (x *RolePermission) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermission.ProtoReflect.Descriptor instead.
func (*RolePermission) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{15}
}

func (x *RolePermission) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolePermission) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// Principal is a resolvable identity and the grants it holds.
type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id — the user id, or the API key id for an agent credential.
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Human-readable subject for logs and audit. Never used for authorization.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Already intersected for an API key (ADR 0014), so the data plane never
	// has to remember to do it. There is one way to get effective grants, and
	// this is it.
	Grants []*Grant `protobuf:"bytes,4,rep,name=grants,proto3" json:"grants,omitempty"`
	// The credential this principal is reached by. A snapshot's principals are
	// its API keys — one per key, not one per user — because a user with no key
	// cannot reach the data plane at all, and publishing an unreachable
	// principal would only make the artifact bigger.
	//
	// key_prefix is the public, indexed half. key_secret_sha256 is a digest of
	// 192 CSPRNG bits, which is what lets the data plane verify a credential
	// with one hash and no database (ADR 0021). It is not an Argon2id hash and
	// must not become one: that runs on the request path.
	KeyPrefix       string `protobuf:"bytes,5,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	KeySecretSha256 string `protobuf:"bytes,6,opt,name=key_secret_sha256,json=keySecretSha256,proto3" json:"key_secret_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{16}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Principal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Principal) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *Principal) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *Principal) GetKeySecretSha256() string {
	if x != nil {
		return x.KeySecretSha256
	}
	return ""
}

// Grant is a Casbin `g` policy: a role held within a scope.
type Grant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Hierarchical scope: `*`, `t/<tenant>`, `t/<tenant>/ts/<toolset>`, or
	// `t/<tenant>/ts/<toolset>/<tool>`.
	Scope         string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{17}
}

func (x *Grant) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Grant) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Rules         []*PolicyRule          `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{18}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Policy) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type PolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Match conditions. An empty field matches anything.
	EffectClasses       []string `protobuf:"bytes,1,rep,name=effect_classes,json=effectClasses,proto3" json:"effect_classes,omitempty"` // effect class names
	QualifiedNameGlobs  []string `protobuf:"bytes,2,rep,name=qualified_name_globs,json=qualifiedNameGlobs,proto3" json:"qualified_name_globs,omitempty"`
	NamespaceIds        []string `protobuf:"bytes,3,rep,name=namespace_ids,json=namespaceIds,proto3" json:"namespace_ids,omitempty"`
	RequiredIdpGroups   []string `protobuf:"bytes,4,rep,name=required_idp_groups,json=requiredIdpGroups,proto3" json:"required_idp_groups,omitempty"`
	DataClassifications []string `protobuf:"bytes,5,rep,name=data_classifications,json=dataClassifications,proto3" json:"data_classifications,omitempty"`
	// Decision when the rule matches.
	Decision PolicyDecision `protobuf:"varint,6,opt,name=decision,proto3,enum=mcpdoll.snapshot.v1.PolicyDecision" json:"decision,omitempty"`
	Reason   string         `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional TTL narrowing applied to list results this rule touches.
	MaxTtlMs int32 `protobuf:"varint,8,opt,name=max_ttl_ms,json=maxTtlMs,proto3" json:"max_ttl_ms,omitempty"`
	// Whether matching this rule makes the catalog view identity-specific, and
	// therefore un-shareable between principals.
	IdentitySpecific bool `protobuf:"varint,9,opt,name=identity_specific,json=identitySpecific,proto3" json:"identity_specific,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{19}
}

func (x *PolicyRule) GetEffectClasses() []string {
	if x != nil {
		return x.EffectClasses
	}
	return nil
}

func (x *PolicyRule) GetQualifiedNameGlobs() []string {
	if x != nil {
		return x.QualifiedNameGlobs
	}
	return nil
}

func (x *PolicyRule) GetNamespaceIds() []string {
	if x != nil {
		return x.NamespaceIds
	}
	return nil
}

func (x *PolicyRule) GetRequiredIdpGroups() []string {
	if x != nil {
		return x.RequiredIdpGroups
	}
	return nil
}

func (x *PolicyRule) GetDataClassifications() []string {
	if x != nil {
		return x.DataClassifications
	}
	return nil
}

func (x *PolicyRule) GetDecision() PolicyDecision {
	if x != nil {
		return x.Decision
	}
	return PolicyDecision_POLICY_DECISION_UNSPECIFIED
}

func (x *PolicyRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyRule) GetMaxTtlMs() int32 {
	if x != nil {
		return x.MaxTtlMs
	}
	return 0
}

func (x *PolicyRule) GetIdentitySpecific() bool {
	if x != nil {
		return x.IdentitySpecific
	}
	return false
}

type PluginManifest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Runtime PluginRuntime          `protobuf:"varint,4,opt,name=runtime,proto3,enum=mcpdoll.snapshot.v1.PluginRuntime" json:"runtime,omitempty"`
	// Hooks this plugin participates in.
	Hooks []Hook `protobuf:"varint,5,rep,packed,name=hooks,proto3,enum=mcpdoll.snapshot.v1.Hook" json:"hooks,omitempty"`
	// Lower runs first within a hook. Two mutating plugins may not share a
	// priority at the same hook; the snapshot build rejects that rather than
	// leaving the order to map iteration.
	Priority int32 `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	// Per-invocation deadline. Zero means the pipeline default.
	BudgetMs int32 `protobuf:"varint,7,opt,name=budget_ms,json=budgetMs,proto3" json:"budget_ms,omitempty"`
	// Declared scopes. A plugin may read only what it declares and may patch
	// only within `writes`; a patch outside that scope is rejected at runtime,
	// so the manifest is an enforced contract rather than documentation.
	Reads  []string `protobuf:"bytes,8,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes []string `protobuf:"bytes,9,rep,name=writes,proto3" json:"writes,omitempty"`
	// Failure mode per effect class, keyed by EffectClass name. A plugin is
	// usually fail-open on reads and fail-closed on destructive calls, and that
	// asymmetry has to be expressed per class rather than per plugin.
	FailurePolicy map[string]FailureMode `protobuf:"bytes,10,rep,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=mcpdoll.snapshot.v1.FailureMode"`
	// Whether this plugin's output depends on who is asking. If true, any catalog
	// it touches becomes cacheScope: private, because a response shaped for one
	// principal must never be served to another.
	IdentityDependent bool         `protobuf:"varint,11,opt,name=identity_dependent,json=identityDependent,proto3" json:"identity_dependent,omitempty"`
	Rollout           RolloutState `protobuf:"varint,12,opt,name=rollout,proto3,enum=mcpdoll.snapshot.v1.RolloutState" json:"rollout,omitempty"`
	// Percentage 0..100, meaningful only for ROLLOUT_STATE_CANARY.
	CanaryPercent int32 `protobuf:"varint,13,opt,name=canary_percent,json=canaryPercent,proto3" json:"canary_percent,omitempty"`
	// Artifact location and digest. The digest is verified before load, so a
	// swapped artifact fails closed.
	ArtifactRef    string `protobuf:"bytes,14,opt,name=artifact_ref,json=artifactRef,proto3" json:"artifact_ref,omitempty"`
	ArtifactDigest string `protobuf:"bytes,15,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	// WASM fuel limit — bounded CPU rather than a wall-clock timeout, so a busy
	// host does not turn a compute limit into a flaky one.
	FuelLimit uint64 `protobuf:"varint,16,opt,name=fuel_limit,json=fuelLimit,proto3" json:"fuel_limit,omitempty"`
	// gRPC endpoint, for PLUGIN_RUNTIME_GRPC.
	Endpoint string `protobuf:"bytes,17,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Opaque plugin configuration as canonical JSON.
	ConfigJson string `protobuf:"bytes,18,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// Restrict this plugin to specific toolsets. Empty means every tool.
	ToolsetIds    []string `protobuf:"bytes,19,rep,name=toolset_ids,json=toolsetIds,proto3" json:"toolset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{20}
}

func (x *PluginManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetRuntime() PluginRuntime {
	if x != nil {
		return x.Runtime
	}
	return PluginRuntime_PLUGIN_RUNTIME_UNSPECIFIED
}

func (x *PluginManifest) GetHooks() []Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginManifest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PluginManifest) GetBudgetMs() int32 {
	if x != nil {
		return x.BudgetMs
	}
	return 0
}

func (x *PluginManifest) GetReads() []string {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *PluginManifest) GetWrites() []string {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *PluginManifest) GetFailurePolicy() map[string]FailureMode {
	if x != nil {
		return x.FailurePolicy
	}
	return nil
}

func (x *PluginManifest) GetIdentityDependent() bool {
	if x != nil {
		return x.IdentityDependent
	}
	return false
}

func (x *PluginManifest) GetRollout() RolloutState {
	if x != nil {
		return x.Rollout
	}
	return RolloutState_ROLLOUT_STATE_UNSPECIFIED
}

func (x *PluginManifest) GetCanaryPercent() int32 {
	if x != nil {
		return x.CanaryPercent
	}
	return 0
}

func (x *PluginManifest) GetArtifactRef() string {
	if x != nil {
		return x.ArtifactRef
	}
	return ""
}

func (x *PluginManifest) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *PluginManifest) GetFuelLimit() uint64 {
	if x != nil {
		return x.FuelLimit
	}
	return 0
}

func (x *PluginManifest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PluginManifest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *PluginManifest) GetToolsetIds() []string {
	if x != nil {
		return x.ToolsetIds
	}
	return nil
}

var File_mcpdoll_snapshot_v1_snapshot_proto protoreflect.FileDescriptor

const file_mcpdoll_snapshot_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\"mcpdoll/snapshot/v1/snapshot.proto\x12\x13mcpdoll.snapshot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x0eSignedSnapshot\x12%\n" +
	"\x0esnapshot_bytes\x18\x01 \x01(\fR\rsnapshotBytes\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"\x84\x01\n" +
	"\x12SignedPrincipalSet\x12\x1b\n" +
	"\tset_bytes\x18\x01 \x01(\fR\bsetBytes\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"\xf1\x01\n" +
	"\fPrincipalSet\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12N\n" +
	"\x10role_permissions\x18\x03 \x03(\v2#.mcpdoll.snapshot.v1.RolePermissionR\x0frolePermissions\x12>\n" +
	"\n" +
	"principals\x18\x04 \x03(\v2\x1e.mcpdoll.snapshot.v1.PrincipalR\n" +
	"principals\"\x88\x01\n" +
	"\x14SignedRevocationList\x12\x1d\n" +
	"\n" +
	"list_bytes\x18\x01 \x01(\fR\tlistBytes\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"\xcf\x01\n" +
	"\x0eRevocationList\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12#\n" +
	"\rprincipal_ids\x18\x03 \x03(\tR\fprincipalIds\x12E\n" +
	"\x1fpruned_through_snapshot_version\x18\x04 \x01(\x03R\x1cprunedThroughSnapshotVersion\"\xa3\x05\n" +
	"\bSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x125\n" +
	"\bbuilt_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\abuiltAt\x12'\n" +
	"\x0fregistry_digest\x18\x05 \x01(\tR\x0eregistryDigest\x12>\n" +
	"\n" +
	"namespaces\x18\x06 \x03(\v2\x1e.mcpdoll.snapshot.v1.NamespaceR\n" +
	"namespaces\x125\n" +
	"\aservers\x18\a \x03(\v2\x1b.mcpdoll.snapshot.v1.ServerR\aservers\x129\n" +
	"\x05tools\x18\b \x03(\v2#.mcpdoll.snapshot.v1.ToolDefinitionR\x05tools\x127\n" +
	"\bpolicies\x18\v \x03(\v2\x1b.mcpdoll.snapshot.v1.PolicyR\bpolicies\x12=\n" +
	"\aplugins\x18\f \x03(\v2#.mcpdoll.snapshot.v1.PluginManifestR\aplugins\x12>\n" +
	"\acatalog\x18\r \x01(\v2$.mcpdoll.snapshot.v1.CatalogDefaultsR\acatalog\x125\n" +
	"\atenants\x18\x0e \x03(\v2\x1b.mcpdoll.snapshot.v1.TenantR\atenants\x128\n" +
	"\btoolsets\x18\x0f \x03(\v2\x1c.mcpdoll.snapshot.v1.ToolsetR\btoolsetsJ\x04\b\x04\x10\x05J\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\x10\x10\x11R\x06org_idR\abundlesR\taudiences\"P\n" +
	"\x0fCatalogDefaults\x12\x15\n" +
	"\x06ttl_ms\x18\x01 \x01(\x05R\x05ttlMs\x12&\n" +
	"\x0fdegraded_ttl_ms\x18\x02 \x01(\x05R\rdegradedTtlMs\"\xb4\x01\n" +
	"\tNamespace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12$\n" +
	"\x0eowning_team_id\x18\x04 \x01(\tR\fowningTeamId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12&\n" +
	"\x0fowner_idp_group\x18\x06 \x01(\tR\rownerIdpGroup\"\x9f\x05\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fnamespace_id\x18\x03 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x126\n" +
	"\x17pinned_protocol_version\x18\x06 \x01(\tR\x15pinnedProtocolVersion\x12C\n" +
	"\fserving_mode\x18\a \x01(\x0e2 .mcpdoll.snapshot.v1.ServingModeR\vservingMode\x12 \n" +
	"\vcriticality\x18\b \x01(\tR\vcriticality\x12/\n" +
	"\x13data_classification\x18\t \x01(\tR\x12dataClassification\x12)\n" +
	"\x10compliance_scope\x18\n" +
	" \x03(\tR\x0fcomplianceScope\x12$\n" +
	"\x0eowning_team_id\x18\v \x01(\tR\fowningTeamId\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12I\n" +
	"\x0etoken_exchange\x18\r \x01(\v2\".mcpdoll.snapshot.v1.TokenExchangeR\rtokenExchange\x129\n" +
	"\x06health\x18\x0e \x01(\v2!.mcpdoll.snapshot.v1.HealthPolicyR\x06health\x12\x1f\n" +
	"\vcanary_tool\x18\x0f \x01(\tR\n" +
	"canaryTool\x128\n" +
	"\bbindings\x18\x10 \x03(\v2\x1c.mcpdoll.snapshot.v1.BindingR\bbindingsJ\x04\b\x05\x10\x06R\bendpoint\"\xd2\x02\n" +
	"\rTokenExchange\x12%\n" +
	"\x0etoken_endpoint\x18\x01 \x01(\tR\rtokenEndpoint\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x122\n" +
	"\x15client_credential_ref\x18\x04 \x01(\tR\x13clientCredentialRef\x12\x16\n" +
	"\x06header\x18\x05 \x01(\tR\x06header\x12Y\n" +
	"\rclaim_headers\x18\x06 \x03(\v24.mcpdoll.snapshot.v1.TokenExchange.ClaimHeadersEntryR\fclaimHeaders\x1a?\n" +
	"\x11ClaimHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\fHealthPolicy\x12*\n" +
	"\x11probe_interval_ms\x18\x01 \x01(\x05R\x0fprobeIntervalMs\x12(\n" +
	"\x10probe_timeout_ms\x18\x02 \x01(\x05R\x0eprobeTimeoutMs\x12&\n" +
	"\x0fgrace_window_ms\x18\x03 \x01(\x05R\rgraceWindowMs\x120\n" +
	"\x14eject_after_failures\x18\x04 \x01(\x05R\x12ejectAfterFailures\"\xeb\x04\n" +
	"\x0eToolDefinition\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12'\n" +
	"\x0fsemantic_digest\x18\x02 \x01(\tR\x0esemanticDigest\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12!\n" +
	"\fnamespace_id\x18\x04 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\ttenant_id\x18\x0f \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"toolset_id\x18\x10 \x01(\tR\ttoolsetId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x06 \x01(\tR\rqualifiedName\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\t \x01(\tR\x0finputSchemaJson\x12,\n" +
	"\x12output_schema_json\x18\n" +
	" \x01(\tR\x10outputSchemaJson\x12)\n" +
	"\x10annotations_json\x18\v \x01(\tR\x0fannotationsJson\x12C\n" +
	"\feffect_class\x18\f \x01(\x0e2 .mcpdoll.snapshot.v1.EffectClassR\veffectClass\x12%\n" +
	"\x0etoken_estimate\x18\r \x01(\x05R\rtokenEstimate\x128\n" +
	"\x18requires_idempotency_key\x18\x0e \x01(\bR\x16requiresIdempotencyKey\"X\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\\\n" +
	"\aBinding\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\tR\breplicas\"\x83\x01\n" +
	"\aToolset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\ftoken_budget\x18\x04 \x01(\x05R\vtokenBudget\x12\x15\n" +
	"\x06ttl_ms\x18\x05 \x01(\x05R\x05ttlMs\"D\n" +
	"\x0eRolePermission\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\"\xd1\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x122\n" +
	"\x06grants\x18\x04 \x03(\v2\x1a.mcpdoll.snapshot.v1.GrantR\x06grants\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x05 \x01(\tR\tkeyPrefix\x12*\n" +
	"\x11key_secret_sha256\x18\x06 \x01(\tR\x0fkeySecretSha256\"1\n" +
	"\x05Grant\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\x7f\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x125\n" +
	"\x05rules\x18\x04 \x03(\v2\x1f.mcpdoll.snapshot.v1.PolicyRuleR\x05rules\"\x91\x03\n" +
	"\n" +
	"PolicyRule\x12%\n" +
	"\x0eeffect_classes\x18\x01 \x03(\tR\reffectClasses\x120\n" +
	"\x14qualified_name_globs\x18\x02 \x03(\tR\x12qualifiedNameGlobs\x12#\n" +
	"\rnamespace_ids\x18\x03 \x03(\tR\fnamespaceIds\x12.\n" +
	"\x13required_idp_groups\x18\x04 \x03(\tR\x11requiredIdpGroups\x121\n" +
	"\x14data_classifications\x18\x05 \x03(\tR\x13dataClassifications\x12?\n" +
	"\bdecision\x18\x06 \x01(\x0e2#.mcpdoll.snapshot.v1.PolicyDecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1c\n" +
	"\n" +
	"max_ttl_ms\x18\b \x01(\x05R\bmaxTtlMs\x12+\n" +
	"\x11identity_specific\x18\t \x01(\bR\x10identitySpecific\"\xc3\x06\n" +
	"\x0ePluginManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12<\n" +
	"\aruntime\x18\x04 \x01(\x0e2\".mcpdoll.snapshot.v1.PluginRuntimeR\aruntime\x12/\n" +
	"\x05hooks\x18\x05 \x03(\x0e2\x19.mcpdoll.snapshot.v1.HookR\x05hooks\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tbudget_ms\x18\a \x01(\x05R\bbudgetMs\x12\x14\n" +
	"\x05reads\x18\b \x03(\tR\x05reads\x12\x16\n" +
	"\x06writes\x18\t \x03(\tR\x06writes\x12]\n" +
	"\x0efailure_policy\x18\n" +
	" \x03(\v26.mcpdoll.snapshot.v1.PluginManifest.FailurePolicyEntryR\rfailurePolicy\x12-\n" +
	"\x12identity_dependent\x18\v \x01(\bR\x11identityDependent\x12;\n" +
	"\arollout\x18\f \x01(\x0e2!.mcpdoll.snapshot.v1.RolloutStateR\arollout\x12%\n" +
	"\x0ecanary_percent\x18\r \x01(\x05R\rcanaryPercent\x12!\n" +
	"\fartifact_ref\x18\x0e \x01(\tR\vartifactRef\x12'\n" +
	"\x0fartifact_digest\x18\x0f \x01(\tR\x0eartifactDigest\x12\x1d\n" +
	"\n" +
	"fuel_limit\x18\x10 \x01(\x04R\tfuelLimit\x12\x1a\n" +
	"\bendpoint\x18\x11 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vconfig_json\x18\x12 \x01(\tR\n" +
	"configJson\x12\x1f\n" +
	"\vtoolset_ids\x18\x13 \x03(\tR\n" +
	"toolsetIds\x1ab\n" +
	"\x12FailurePolicyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\x0e2 .mcpdoll.snapshot.v1.FailureModeR\x05value:\x028\x01*x\n" +
	"\vEffectClass\x12\x1c\n" +
	"\x18EFFECT_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EFFECT_CLASS_READ\x10\x01\x12\x16\n" +
	"\x12EFFECT_CLASS_WRITE\x10\x02\x12\x1c\n" +
	"\x18EFFECT_CLASS_DESTRUCTIVE\x10\x03*_\n" +
	"\vServingMode\x12\x1c\n" +
	"\x18SERVING_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVING_MODE_STRICT\x10\x01\x12\x19\n" +
	"\x15SERVING_MODE_ADVISORY\x10\x02*\x9d\x01\n" +
	"\x0ePolicyDecision\x12\x1f\n" +
	"\x1bPOLICY_DECISION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POLICY_DECISION_ALLOW\x10\x01\x12\x18\n" +
	"\x14POLICY_DECISION_DENY\x10\x02\x12\x18\n" +
	"\x14POLICY_DECISION_HIDE\x10\x03\x12\x1b\n" +
	"\x17POLICY_DECISION_CONFIRM\x10\x04*\xb5\x01\n" +
	"\x04Hook\x12\x14\n" +
	"\x10HOOK_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHOOK_ON_REQUEST\x10\x01\x12\x14\n" +
	"\x10HOOK_ON_IDENTITY\x10\x02\x12\x13\n" +
	"\x0fHOOK_ON_CATALOG\x10\x03\x12\x15\n" +
	"\x11HOOK_ON_TOOL_CALL\x10\x04\x12\x17\n" +
	"\x13HOOK_ON_TOOL_RESULT\x10\x05\x12\x14\n" +
	"\x10HOOK_ON_RESPONSE\x10\x06\x12\x11\n" +
	"\rHOOK_ON_AUDIT\x10\a*a\n" +
	"\rPluginRuntime\x12\x1e\n" +
	"\x1aPLUGIN_RUNTIME_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PLUGIN_RUNTIME_WASM\x10\x01\x12\x17\n" +
	"\x13PLUGIN_RUNTIME_GRPC\x10\x02*|\n" +
	"\fRolloutState\x12\x1d\n" +
	"\x19ROLLOUT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ROLLOUT_STATE_SHADOW\x10\x01\x12\x18\n" +
	"\x14ROLLOUT_STATE_CANARY\x10\x02\x12\x19\n" +
	"\x15ROLLOUT_STATE_ENFORCE\x10\x03*[\n" +
	"\vFailureMode\x12\x1c\n" +
	"\x18FAILURE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FAILURE_MODE_OPEN\x10\x01\x12\x17\n" +
	"\x13FAILURE_MODE_CLOSED\x10\x02B6Z4github.com/mcpdoll/mcpdoll/internal/proto/snapshotpbb\x06proto3"

var (
	file_mcpdoll_snapshot_v1_snapshot_proto_rawDescOnce sync.Once
	file_mcpdoll_snapshot_v1_snapshot_proto_rawDescData []byte
)

func file_mcpdoll_snapshot_v1_snapshot_proto_rawDescGZIP() []byte {
	file_mcpdoll_snapshot_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_mcpdoll_snapshot_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpdoll_snapshot_v1_snapshot_proto_rawDesc), len(file_mcpdoll_snapshot_v1_snapshot_proto_rawDesc)))
	})
	return file_mcpdoll_snapshot_v1_snapshot_proto_rawDescData
}

var file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_mcpdoll_snapshot_v1_snapshot_proto_goTypes = []any{
	(EffectClass)(0),              // 0: mcpdoll.snapshot.v1.EffectClass
	(ServingMode)(0),              // 1: mcpdoll.snapshot.v1.ServingMode
	(PolicyDecision)(0),           // 2: mcpdoll.snapshot.v1.PolicyDecision
	(Hook)(0),                     // 3: mcpdoll.snapshot.v1.Hook
	(PluginRuntime)(0),            // 4: mcpdoll.snapshot.v1.PluginRuntime
	(RolloutState)(0),             // 5: mcpdoll.snapshot.v1.RolloutState
	(FailureMode)(0),              // 6: mcpdoll.snapshot.v1.FailureMode
	(*SignedSnapshot)(nil),        // 7: mcpdoll.snapshot.v1.SignedSnapshot
	(*SignedPrincipalSet)(nil),    // 8: mcpdoll.snapshot.v1.SignedPrincipalSet
	(*PrincipalSet)(nil),          // 9: mcpdoll.snapshot.v1.PrincipalSet
	(*SignedRevocationList)(nil),  // 10: mcpdoll.snapshot.v1.SignedRevocationList
	(*RevocationList)(nil),        // 11: mcpdoll.snapshot.v1.RevocationList
	(*Snapshot)(nil),              // 12: mcpdoll.snapshot.v1.Snapshot
	(*CatalogDefaults)(nil),       // 13: mcpdoll.snapshot.v1.CatalogDefaults
	(*Namespace)(nil),             // 14: mcpdoll.snapshot.v1.Namespace
	(*Server)(nil),                // 15: mcpdoll.snapshot.v1.Server
	(*TokenExchange)(nil),         // 16: mcpdoll.snapshot.v1.TokenExchange
	(*HealthPolicy)(nil),          // 17: mcpdoll.snapshot.v1.HealthPolicy
	(*ToolDefinition)(nil),        // 18: mcpdoll.snapshot.v1.ToolDefinition
	(*Tenant)(nil),                // 19: mcpdoll.snapshot.v1.Tenant
	(*Binding)(nil),               // 20: mcpdoll.snapshot.v1.Binding
	(*Toolset)(nil),               // 21: mcpdoll.snapshot.v1.Toolset
	(*RolePermission)(nil),        // 22: mcpdoll.snapshot.v1.RolePermission
	(*Principal)(nil),             // 23: mcpdoll.snapshot.v1.Principal
	(*Grant)(nil),                 // 24: mcpdoll.snapshot.v1.Grant
	(*Policy)(nil),                // 25: mcpdoll.snapshot.v1.Policy
	(*PolicyRule)(nil),            // 26: mcpdoll.snapshot.v1.PolicyRule
	(*PluginManifest)(nil),        // 27: mcpdoll.snapshot.v1.PluginManifest
	nil,                           // 28: mcpdoll.snapshot.v1.TokenExchange.ClaimHeadersEntry
	nil,                           // 29: mcpdoll.snapshot.v1.PluginManifest.FailurePolicyEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_mcpdoll_snapshot_v1_snapshot_proto_depIdxs = []int32{
	30, // 0: mcpdoll.snapshot.v1.PrincipalSet.issued_at:type_name -> google.protobuf.Timestamp
	22, // 1: mcpdoll.snapshot.v1.PrincipalSet.role_permissions:type_name -> mcpdoll.snapshot.v1.RolePermission
	23, // 2: mcpdoll.snapshot.v1.PrincipalSet.principals:type_name -> mcpdoll.snapshot.v1.Principal
	30, // 3: mcpdoll.snapshot.v1.RevocationList.issued_at:type_name -> google.protobuf.Timestamp
	30, // 4: mcpdoll.snapshot.v1.Snapshot.built_at:type_name -> google.protobuf.Timestamp
	14, // 5: mcpdoll.snapshot.v1.Snapshot.namespaces:type_name -> mcpdoll.snapshot.v1.Namespace
	15, // 6: mcpdoll.snapshot.v1.Snapshot.servers:type_name -> mcpdoll.snapshot.v1.Server
	18, // 7: mcpdoll.snapshot.v1.Snapshot.tools:type_name -> mcpdoll.snapshot.v1.ToolDefinition
	25, // 8: mcpdoll.snapshot.v1.Snapshot.policies:type_name -> mcpdoll.snapshot.v1.Policy
	27, // 9: mcpdoll.snapshot.v1.Snapshot.plugins:type_name -> mcpdoll.snapshot.v1.PluginManifest
	13, // 10: mcpdoll.snapshot.v1.Snapshot.catalog:type_name -> mcpdoll.snapshot.v1.CatalogDefaults
	19, // 11: mcpdoll.snapshot.v1.Snapshot.tenants:type_name -> mcpdoll.snapshot.v1.Tenant
	21, // 12: mcpdoll.snapshot.v1.Snapshot.toolsets:type_name -> mcpdoll.snapshot.v1.Toolset
	1,  // 13: mcpdoll.snapshot.v1.Server.serving_mode:type_name -> mcpdoll.snapshot.v1.ServingMode
	16, // 14: mcpdoll.snapshot.v1.Server.token_exchange:type_name -> mcpdoll.snapshot.v1.TokenExchange
	17, // 15: mcpdoll.snapshot.v1.Server.health:type_name -> mcpdoll.snapshot.v1.HealthPolicy
	20, // 16: mcpdoll.snapshot.v1.Server.bindings:type_name -> mcpdoll.snapshot.v1.Binding
	28, // 17: mcpdoll.snapshot.v1.TokenExchange.claim_headers:type_name -> mcpdoll.snapshot.v1.TokenExchange.ClaimHeadersEntry
	0,  // 18: mcpdoll.snapshot.v1.ToolDefinition.effect_class:type_name -> mcpdoll.snapshot.v1.EffectClass
	24, // 19: mcpdoll.snapshot.v1.Principal.grants:type_name -> mcpdoll.snapshot.v1.Grant
	26, // 20: mcpdoll.snapshot.v1.Policy.rules:type_name -> mcpdoll.snapshot.v1.PolicyRule
	2,  // 21: mcpdoll.snapshot.v1.PolicyRule.decision:type_name -> mcpdoll.snapshot.v1.PolicyDecision
	4,  // 22: mcpdoll.snapshot.v1.PluginManifest.runtime:type_name -> mcpdoll.snapshot.v1.PluginRuntime
	3,  // 23: mcpdoll.snapshot.v1.PluginManifest.hooks:type_name -> mcpdoll.snapshot.v1.Hook
	29, // 24: mcpdoll.snapshot.v1.PluginManifest.failure_policy:type_name -> mcpdoll.snapshot.v1.PluginManifest.FailurePolicyEntry
	5,  // 25: mcpdoll.snapshot.v1.PluginManifest.rollout:type_name -> mcpdoll.snapshot.v1.RolloutState
	6,  // 26: mcpdoll.snapshot.v1.PluginManifest.FailurePolicyEntry.value:type_name -> mcpdoll.snapshot.v1.FailureMode
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_mcpdoll_snapshot_v1_snapshot_proto_init() }
func file_mcpdoll_snapshot_v1_snapshot_proto_init() {
	if File_mcpdoll_snapshot_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpdoll_snapshot_v1_snapshot_proto_rawDesc), len(file_mcpdoll_snapshot_v1_snapshot_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcpdoll_snapshot_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_mcpdoll_snapshot_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_mcpdoll_snapshot_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_mcpdoll_snapshot_v1_snapshot_proto_msgTypes,
	}.Build()
	File_mcpdoll_snapshot_v1_snapshot_proto = out.File
	file_mcpdoll_snapshot_v1_snapshot_proto_goTypes = nil
	file_mcpdoll_snapshot_v1_snapshot_proto_depIdxs = nil
}
