// Code generated by tools/gents. DO NOT EDIT.
//
// Every type here comes from a schema in api/openapi.yaml, which ADR 0004 makes
// the source of truth for all three surfaces. It was hand-written until a
// renamed field could compile on this side and read as `undefined` at runtime —
// the Go structs were held against the spec and the console's paths were, but
// nothing checked its field names.
//
// Run `make generate` after editing the spec. `make verify-generated` fails
// the build when this file is stale.

export interface ApiErrorBody {
  /**
   * Stable machine-readable token. Clients switch on this; the message
   * is for humans and may be reworded.
   */
  code: "invalid_request" | "not_found" | "forbidden" | "validation_failed" | "upstream_unavailable" | "internal_error";
  /** One sentence, written for whoever has to fix the problem. */
  message: string;
  /**
   * Every distinct failure. Validation returns all of them at once: a
   * document with six errors should take one round trip to fix.
   */
  problems?: string[];
}

export interface Health {
  status: string;
  version: string;
  /**
   * The document this control plane is serving. Unexpected output is
   * nearly always the wrong file rather than the wrong logic.
   */
  registry_path?: string;
  snapshot_path?: string;
}

export interface HookList {
  /** The seven hooks, in execution order. The set is closed. */
  hooks: string[];
}

/**
 * A registry document with defaults resolved. Not the on-disk YAML: an
 * unset `serving_mode` reads as `strict` here because that is what the
 * engine will do, and rule bodies are summarised to counts.
 */
export interface Registry {
  org: string;
  version: number;
  namespaces: Namespace[];
  servers: Server[];
  toolsets: Toolset[];
  policies?: Policy[];
  plugins?: Plugin[];
}

export interface Namespace {
  id: string;
  name: string;
  /**
   * What every tool in this namespace is served under, and why two
   * namespaces cannot share one.
   */
  prefix: string;
  owner_idp_group?: string;
  team?: string;
  project?: string;
}

export interface Server {
  id: string;
  name: string;
  namespace: string;
  bindings: Binding[];
  /**
   * Resolved, never empty. `strict` refuses to serve a definition that
   * has drifted from what was admitted; `advisory` serves it and
   * records the drift.
   */
  serving_mode: "strict" | "advisory";
  criticality?: string;
  data_classification?: string;
  compliance_scope?: string[];
  default_effect_class: "read" | "write" | "destructive";
  /**
   * Probed to decide whether this backend is healthy, rather than
   * trusting a transport-level ping.
   */
  canary_tool?: string;
  /**
   * Tools whose effect class the registry states explicitly. Everything
   * else inherits `default_effect_class`.
   */
  tool_overrides?: Record<string, string>;
  /**
   * Withheld from every toolset. Kept separate from `tool_overrides`
   * because an exclusion is not an override with a blank class — the
   * tool does not reach the snapshot at all.
   */
  excluded_tools?: string[];
}

/**
 * A named, grantable group of tools. It replaced the old bundle, and the
 * rename carries meaning: a bundle grouped
 * namespaces for publication, whereas a toolset is the unit an
 * administrator hands to a user — and its name appears inside every grant
 * scope, `t/<tenant>/ts/<toolset>`. See ADR 0016.
 */
export interface Toolset {
  id: string;
  name: string;
  /** Leading component of the stable catalog ordering. */
  priority: number;
  token_budget?: number;
  /** Contributes every admitted tool in each named namespace. */
  namespaces: string[];
  /**
   * Individually named tools, qualified. A toolset draws from several
   * namespaces, so a bare name would be ambiguous between them.
   */
  tools?: string[];
  exclude?: string[];
}

/**
 * One tenant's hosts for a backend. The same logical backend is a
 * different deployment per tenant, and each is discovered and admitted
 * separately (ADR 0017).
 */
export interface Binding {
  tenant: string;
  /**
   * The definition source. Replicas are compared against it; one that
   * diverges leaves the routable pool without changing the catalog.
   */
  primary: string;
  replicas?: string[];
}

/**
 * A named rule set, summarised. Rule bodies are not returned: the console
 * renders them from the registry document.
 */
export interface Policy {
  id: string;
  name: string;
  priority: number;
  rule_count: number;
}

export interface Plugin {
  id: string;
  name: string;
  version?: string;
  runtime: "wasm" | "grpc";
  hooks: string[];
  priority: number;
  /**
   * Resolved, never empty. An unset rollout means `shadow`; reporting
   * an empty value would make an inert plugin indistinguishable from an
   * enforcing one.
   */
  rollout: "shadow" | "canary" | "enforce";
  canary_percent?: number;
  reads?: string[];
  /**
   * The only paths this plugin may patch. A patch touching anything
   * else is rejected whole, not partially applied.
   */
  writes?: string[];
  /**
   * Forces `cacheScope: private` at `on_catalog`. A catalog shaped by
   * who is asking must never be cached publicly.
   */
  identity_dependent?: boolean;
  /**
   * Checked before load. A mismatch refuses the plugin, which is what
   * makes a swapped artifact fail closed.
   */
  artifact_digest?: string;
}

export interface ServerList {
  servers: Server[];
}

export interface PluginList {
  plugins: Plugin[];
}

export interface RegistrySummary {
  file?: string;
  valid: boolean;
  org: string;
  version: number;
  namespaces: number;
  servers: number;
  toolsets: number;
  policies: number;
  plugins: number;
}

export interface ValidateRegistryRequest {
  /**
   * The registry document as YAML. Validation runs against what the
   * caller sends rather than what is on the server's disk, which is
   * what makes this usable as a pull-request check.
   */
  content: string;
}

export interface Snapshot {
  /**
   * Where these bytes came from — a file path, or `uploaded`. Two
   * snapshots that differ only in origin are otherwise
   * indistinguishable, and that is exactly when it matters.
   */
  source?: string;
  version: number;
  snapshot_id: string;
  org: string;
  built_at: string;
  age: string;
  key_id: string;
  algorithm: string;
  registry_digest: string;
  /**
   * Whether this snapshot would actually activate. A correctly signed
   * snapshot with a dangling reference is refused by every data-plane
   * instance, so signature validity alone is not the question anybody
   * wants answered.
   */
  servable: boolean;
  unservable_reason?: string;
  tenants: TenantSnapshotSummary[];
  tools?: ToolSummary[];
}

/**
 * One tenant's slice of a snapshot. What any given principal in that
 * tenant sees is a subset, decided by their grants.
 */
export interface TenantSnapshotSummary {
  slug: string;
  name: string;
  tools: number;
  token_estimate: number;
}

export interface ToolSummary {
  qualified_name: string;
  backend: string;
  effect_class: "read" | "write" | "destructive";
  token_estimate: number;
  digest: string;
}

export interface InspectSnapshotRequest {
  /**
   * The signed snapshot, base64-encoded. The bytes travel in the
   * request rather than a path travelling in it: a server that opens
   * whatever file a caller names is an arbitrary file read.
   */
  content: string;
  /** List every tool rather than summarising by tenant. */
  tools?: boolean;
}

export interface VerifySnapshotRequest {
  content: string;
  /**
   * `keyID:base64PublicKey` entries, supplied by the caller rather than
   * taken from server config — so this answers "would *that* data plane
   * accept it?" for any data plane, not only the local one.
   */
  trusted_keys: string[];
}

export interface VerifyReport {
  source?: string;
  valid: boolean;
  version: number;
  key_id: string;
  tenants: string[];
  tools: number;
}

/**
 * The registry and the signing key come from the server's configuration,
 * not from this body. A caller who could name either could publish
 * arbitrary configuration signed by the control plane's key.
 */
export interface BuildSnapshotRequest {
  /**
   * Build even if a backend is down, omitting its tools. Tools from a
   * merely temporarily-down backend would vanish from every catalog and
   * invalidate clients' prompt caches, so this is for publishing around
   * a decommissioned backend, not around an outage.
   */
  allow_unreachable?: boolean;
  /** Validate and report without writing the snapshot file. */
  dry_run?: boolean;
  discover_timeout_ms?: number;
  concurrency?: number;
  /**
   * Overrides the snapshot version. Absent means a Unix timestamp,
   * which is what a grants-only republish wants: monotonic without
   * anybody coordinating, and nothing to forget to bump. The data plane
   * refuses anything no newer than what it is serving.
   */
  version?: number;
}

export interface BuildReport {
  version: number;
  snapshot_id: string;
  org: string;
  registry_digest: string;
  key_id: string;
  /**
   * The trust entry a data plane needs in order to accept what was just
   * built.
   */
  public_key: string;
  namespaces: number;
  servers: number;
  tools: number;
  toolsets: number;
  plugins: number;
  backends: BackendReport[];
  warnings?: string[];
  output?: string;
  dry_run: boolean;
  /**
   * The build produced the catalog already being served, so nothing was
   * published. Distinct from dry_run: this one did all the work and
   * found no reason to publish, which is the ordinary outcome of a
   * rebuild on a timer.
   */
  unchanged?: boolean;
}

export interface Schedule {
  /** Dispatch key and stable identity; a retuned cadence hangs off it. */
  job_type: string;
  name: string;
  /**
   * Only `interval` today. Cron's finest granularity is a minute and the
   * revocation heartbeat runs every thirty seconds, so the cadence that
   * matters most here is one cron cannot express.
   */
  kind: "interval";
  /** A Go duration for an interval schedule — "30s", "1m". */
  spec: string;
  enabled: boolean;
  /**
   * Cannot be deleted, because nothing would recreate it. Still
   * retunable and still possible to switch off.
   */
  system: boolean;
  next_run_at?: string;
  last_run_at?: string;
  /** Why the last run failed, absent when it succeeded. */
  last_error?: string;
  last_duration_ms?: number;
}

export interface ScheduleList {
  schedules: Schedule[];
}

export interface UpdateScheduleRequest {
  /** New cadence as a Go duration. Omitted leaves it alone. */
  spec?: string;
  /** Omitted leaves it alone, so either can change without the other. */
  enabled?: boolean;
}

/**
 * What discovery found at one backend. There is no `reachable` field and
 * no error field: a backend that could not be reached fails the build
 * unless `allow_unreachable` was set, in which case it appears in
 * `warnings`. A per-backend error here would suggest a snapshot can be
 * partly successful, and it cannot.
 */
export interface BackendReport {
  server_id: string;
  server_name: string;
  endpoint: string;
  /**
   * The MCP version this backend actually agreed to — how a legacy
   * backend becomes visible without anyone declaring it legacy.
   */
  negotiated_version?: string;
  tool_count: number;
  admitted: string[];
  excluded?: string[];
  observed_at: string;
}

export interface GenerateSigningKeyRequest {
  /**
   * Recorded in every snapshot this key signs, and how a verifier
   * selects the right public key during a rotation. Letters, digits,
   * hyphen, underscore — it becomes a filename.
   */
  key_id: string;
}

/**
 * The public half only. The private key is written to the control plane's
 * key directory and never returned: whoever holds it can publish
 * configuration to every data-plane instance, and an HTTP response lands
 * in browser memory, a proxy log, and whatever the client does next.
 */
export interface SigningKey {
  key_id: string;
  directory: string;
  public_key: string;
  /** The exact line to paste into a data plane's `trusted_signing_keys`. */
  trust_entry: string;
}

export interface GatewayStatus {
  gateway_url: string;
  status: string;
  ready: boolean;
  /**
   * What is being served. Two instances reporting different versions is
   * the signal that a rollout is mid-flight.
   */
  snapshot_version: number;
  /**
   * Tenants the gateway is serving. Replaces the audience count: with
   * one endpoint and per-principal catalogs, "how many audiences" no
   * longer describes anything (ADR 0019).
   */
  tenants: number;
  tools: number;
  /** The revocation list this instance is applying. */
  revocations_version?: number;
  /**
   * How long ago that list was issued. The exposure window for a revoked
   * credential, and the number to alert on (ADR 0023).
   */
  revocations_age_seconds?: number;
  revoked_principals?: number;
  /**
   * How long ago the catalog was last rebuilt from the backends — not
   * how long ago it last changed. A version only moves on change, so on
   * its own it cannot tell a quiet deployment from a rebuild loop that
   * has died. This grows in exactly one case (ADR 0025).
   */
  catalog_age_seconds?: number;
  /**
   * The last rebuild failure, absent when the last one succeeded.
   * Reported rather than only logged: a rebuild failing for an hour is
   * invisible in a log nobody is tailing.
   */
  catalog_error?: string;
}

export interface TenantList extends GatewayStatus {
  registered: TenantSummary[];
}

/**
 * Email and password. No tenant: an email identifies one person across the
 * install, and which tenants they reach is what their grants say.
 */
export interface LoginRequest {
  email: string;
  password: string;
}

export interface Session {
  /**
   * The only place this appears. Stored as a SHA-256 digest of CSPRNG
   * output, so nothing can show it again.
   */
  token: string;
  expires_at: string;
  user: User;
  grants: Grant[];
}

export interface SessionInfo {
  /**
   * How the caller authenticated. `static` is the break-glass
   * configuration token, which holds platform_admin at `*` — it exists
   * so CI can build a snapshot before any user does, and every use of it
   * is logged.
   */
  kind: "session" | "api_key" | "static";
  subject: string;
  tenant?: string;
  user_id?: string;
  grants: Grant[];
  /** Held at global scope only. */
  permissions: string[];
}

export interface RevocationReport {
  /** What the control plane last published. */
  version: number;
  /**
   * What the gateway is applying. Behind `version` means a revoked
   * credential is still working.
   */
  serving_version: number;
  /** The exposure window for a revoked credential. */
  serving_age_seconds: number;
  /** Has what was published reached the gateway? */
  in_effect: boolean;
  /**
   * The snapshot version that already reflects everything dropped from
   * the list, so carrying those entries would only make it bigger.
   */
  pruned_through: number;
  path?: string;
  warning?: string;
  revocations: Revocation[];
}

export interface Revocation {
  /**
   * The id the snapshot addresses the principal by — a key id or a
   * session id. Ids, not grants: there is nothing here that could
   * authorize anything.
   */
  principal_id: string;
  kind: "api_key" | "session";
  user_id?: string;
  reason?: string;
  revoked_at: string;
}

/**
 * One tenant, joined across the database, the registry, and the serving
 * snapshot. `users` of zero with a positive `backends` is a tenant nothing
 * can authenticate into; `backends` of zero is a tenant no tool can reach
 * whatever grants its users hold.
 */
export interface TenantSummary {
  /** Absent for a slug that appears only in the registry. */
  id?: string;
  slug: string;
  name: string;
  /**
   * The tenant's own status, or `unregistered` for a slug the registry
   * binds but nobody created.
   */
  status: string;
  users: number;
  /** Registry bindings naming this tenant. */
  backends: number;
  /** Tools the serving snapshot admits for this tenant. */
  tools: number;
  created_at?: string;
}

export interface Tenant {
  id: string;
  /**
   * Appears verbatim in every scope string this tenant's grants use, and
   * is immutable for that reason.
   */
  slug: string;
  name: string;
  status: string;
  created_at: string;
}

export interface CreateTenantRequest {
  slug: string;
  name: string;
}

/**
 * A person. Not a person in a tenant — which tenants they reach is what
 * their grants say, and which tenant an agent session resolves to is what
 * the key says.
 */
export interface User {
  id: string;
  email: string;
  display_name?: string;
  status: "active" | "disabled";
  /**
   * Whether local sign-in is possible. Never the hash — that is the only
   * thing safe to say and the only thing any caller needs.
   */
  has_password: boolean;
  created_at: string;
}

export interface UserList {
  /**
   * Set when the listing was scoped to one tenant — those are the users
   * *granted into* it. Absent for the global listing.
   */
  tenant?: string;
  users: User[];
}

export interface CreateUserRequest {
  email: string;
  display_name?: string;
  /**
   * Optional. A user who signs in through an identity provider has none,
   * and a service identity that only holds API keys does not need one.
   */
  password?: string;
}

export interface UpdateUserRequest {
  display_name?: string;
  status: "active" | "disabled";
}

/**
 * One role held at one scope. Scopes nest: `*` covers everything,
 * `t/<tenant>` covers a tenant, `t/<tenant>/ts/<toolset>` a toolset, and
 * `t/<tenant>/ts/<toolset>/<tool>` a single tool.
 *
 * The tool segment is the backend's own tool name, not the qualified name
 * a client sees — `lookup_customer`, not `crm.lookup_customer`. The prefix
 * belongs to the namespace, so a scope carrying it authorizes nothing;
 * `putGrants` refuses that form rather than storing it.
 */
export interface Grant {
  role: string;
  scope: string;
}

export interface GrantList {
  user_id: string;
  grants: Grant[];
}

export interface PutGrantsRequest {
  /** The complete set the user should hold. Anything absent is revoked. */
  grants: Grant[];
}

export interface APIKey {
  id: string;
  user_id: string;
  /**
   * The tenant this key acts in. On the key rather than on its owner:
   * an MCP session must resolve to exactly one tenant or tool names
   * collide, while a person may legitimately reach several.
   */
  tenant: string;
  name: string;
  /**
   * The lookup half of the key, public by construction: it identifies
   * the row before anything is verified.
   */
  prefix: string;
  /**
   * What the key asks for. Effective grants are this intersected with
   * the owner's, so a key can narrow but never widen.
   */
  declared_grants: Grant[];
  /**
   * Whether this key would authenticate right now — not derivable from
   * any single timestamp below.
   */
  active: boolean;
  created_at: string;
  last_used_at?: string;
  expires_at?: string;
  revoked_at?: string;
}

export interface APIKeyList {
  user_id: string;
  keys: APIKey[];
}

export interface MintAPIKeyRequest {
  /**
   * The tenant this key acts in. Must be one its owner holds a grant
   * reaching, or the key resolves to an empty catalog.
   */
  tenant: string;
  name: string;
  grants?: Grant[];
  /** Absent means the key does not expire. */
  expires_at?: string;
}

export interface MintedAPIKey {
  key: APIKey;
  /**
   * The only place this will ever appear. Stored as an Argon2id hash, so
   * a caller who does not capture it has to mint another key.
   */
  secret: string;
}

export interface Role {
  name: string;
  permissions: string[];
}

export interface RoleCatalog {
  roles: Role[];
  /**
   * Every permission that exists, not only the ones some role uses.
   * The difference is what a console can show as unreachable: a
   * permission no role grants is an operation nobody can perform.
   */
  permissions: string[];
}

export interface BackendHealthReport {
  summary: BackendHealthSummary;
  backends: BackendHealth[];
}

export interface BackendHealthSummary {
  total: number;
  healthy: number;
  degraded: number;
  unavailable: number;
  drifted: number;
  unknown: number;
  /**
   * Tools refused because of drift. Zero in an all-advisory deployment
   * however far its backends have moved.
   */
  blocked_tools: number;
}

export interface BackendHealth {
  server_id: string;
  server_name: string;
  endpoint: string;
  /**
   * `unknown` is distinct from `healthy` on purpose: a gateway that has
   * just started knows nothing about its backends, and reporting that
   * as health would make the first minute after a deploy look better
   * than it is. `degraded` means probes are failing but the grace
   * window has not elapsed, so tools stay listed and their calls fail
   * fast.
   */
  state: "unknown" | "healthy" | "degraded" | "unavailable" | "drifted";
  /**
   * Carried alongside the drift because the same drift means different
   * things under each: strict refuses, advisory serves and records.
   */
  serving_mode: "strict" | "advisory";
  last_probe: string;
  last_success?: string;
  consecutive_failures: number;
  /**
   * Smoothed probe latency. A single slow probe is noise; a rising
   * average is a backend going bad before it starts failing.
   */
  latency_ewma_ms: number;
  negotiated_version?: string;
  error?: string;
  tools_admitted: number;
  tools_observed: number;
  drift?: ToolDrift[];
}

export interface ToolDrift {
  /** The name the backend publishes. */
  name: string;
  /**
   * The name clients see. Absent for an added tool, which has none —
   * assigning one is admission's job, and doing it at runtime would be
   * exactly the auto-naming the design forbids.
   */
  qualified_name?: string;
  /**
   * `cosmetic` is a changed description: the digest differs, the
   * semantic digest does not, and the tool stays servable. `semantic`
   * is a changed schema or annotation — the tool no longer does what
   * was admitted. `removed` and `semantic` are the two that block under
   * strict mode.
   */
  kind: "cosmetic" | "semantic" | "removed" | "added";
  admitted_digest?: string;
  observed_digest?: string;
  /** What changed, so a reader need not diff two digests by eye. */
  detail: string;
}

/**
 * The tool list one identity receives. Produced by making the same
 * request the agent makes, rather than by re-deriving policy — which is
 * how people get this answer wrong.
 */
export interface Catalog {
  tenant: string;
  subject?: string;
  protocol_version: string;
  server_name: string;
  ttl_ms: number;
  cache_scope: "public" | "private";
  tools: CatalogTool[];
}

export interface CatalogTool {
  name: string;
  namespace: string;
  title?: string;
  description?: string;
}

export interface CallToolRequest {
  /**
   * The API key to act as. Inspection presents what the principal
   * presents rather than re-deriving what they should see (ADR 0019).
   */
  credential?: string;
  subject?: string;
  groups?: string[];
  arguments?: Record<string, unknown>;
  /**
   * Continues a deferred call — the signed envelope the gateway issued,
   * echoed back unchanged.
   */
  request_state?: string;
  /**
   * Answers the gateway's input requests, keyed by request id. Each
   * value is `accept`, `decline`, `cancel`, or `text:<value>`.
   */
  responses?: Record<string, string>;
}

export interface CallResult {
  tool: string;
  /**
   * A tool that returned an error is still a successful inspection —
   * the operator asked what happens, and this is what happens. The HTTP
   * status stays 200.
   */
  is_error: boolean;
  /** An MRTR deferral. The call did not fail; it is waiting for a human. */
  needs_input: boolean;
  duration_ms: number;
  text: string;
  /**
   * The gateway's own `_meta` annotation — which plugin mutated the
   * result, which hook denied it. Shaped by the pipeline rather than by
   * this API, so it is returned as-is.
   *
   * Declared open rather than left untyped: a property with no `type` at
   * all is indistinguishable from one somebody forgot to finish, and a
   * generated client has to guess. `additionalProperties: true` says the
   * shape is deliberately not this API's to define.
   */
  gateway_detail?: Record<string, unknown>;
  input_requests?: string[];
  /**
   * The signed envelope to send back with the answers. Unforgeable, not
   * secret: a client can decode it and see what it binds.
   */
  request_state?: string;
}

