// Generates src/routes.gen.ts from src/routes.tsx.
//
// The manifest is generated rather than written so it cannot describe a route
// that does not exist. A hand-maintained list would drift from the router, and
// the drift would be invisible: the parity check would pass while the console
// 404'd.
//
// It parses the source rather than importing it, because importing would need a
// bundler (the module pulls in every screen, and those pull in React). A regex
// over a file whose shape this repository controls is the cheaper honest option
// — and if the shape changes, the generator emits nothing and parity fails
// loudly rather than silently under-reporting.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "src", "routes.tsx");
const target = join(here, "..", "src", "routes.gen.ts");

const raw = readFileSync(source, "utf8");

// Match the { path, operation } pair of each entry. `component` sits between
// them in some entries and after in none, so the lazy gap is bounded to a
// single object literal by excluding braces.
const entry = /path:\s*"([^"]+)",\s*\n\s*operation:\s*"([^"]+)"/g;

const routes = [];
const seen = new Map();
for (const match of raw.matchAll(entry)) {
  const [, path, operation] = match;
  if (seen.has(operation)) {
    console.error(
      `gen-routes: operation "${operation}" is claimed by both ` +
        `${seen.get(operation)} and ${path}`,
    );
    process.exit(1);
  }
  seen.set(operation, path);
  routes.push({ path, operation });
}

if (routes.length === 0) {
  console.error(
    "gen-routes: no routes found in src/routes.tsx — the file's shape changed " +
      "and this generator no longer understands it. Fix the pattern rather " +
      "than shipping an empty manifest.",
  );
  process.exit(1);
}

const body = routes
  .map((r) => `  { path: "${r.path}", operation: "${r.operation}" },`)
  .join("\n");

writeFileSync(
  target,
  `// Code generated by scripts/gen-routes.mjs. DO NOT EDIT.
//
// Read by tools/paritycheck to prove every API operation has a console route.
// Regenerate with \`npm run routes\` (or \`make routes\`) after editing routes.tsx.

export interface RouteBinding {
  path: string;
  operation: string;
}

export const ROUTE_BINDINGS: RouteBinding[] = [
${body}
];
`,
);

console.log(`gen-routes: wrote ${routes.length} bindings to src/routes.gen.ts`);
