// Copyright 2026 Henry Zektser.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: mcpdoll/plugin/v1/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision is the verdict model. Exactly these five: adding a sixth changes
// what the pipeline can express and requires an ADR.
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	// Proceed unchanged.
	Decision_DECISION_ALLOW Decision = 1
	// Refuse the request.
	Decision_DECISION_DENY Decision = 2
	// Proceed with the supplied RFC 6902 patch applied.
	Decision_DECISION_MUTATE Decision = 3
	// Proceed unchanged, but attach metadata for the audit trail and the console.
	Decision_DECISION_ANNOTATE Decision = 4
	// Cannot decide without client input. Becomes an MRTR `input_required`
	// result; the retry re-enters this plugin with the response.
	Decision_DECISION_DEFER Decision = 5
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
		3: "DECISION_MUTATE",
		4: "DECISION_ANNOTATE",
		5: "DECISION_DEFER",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
		"DECISION_MUTATE":      3,
		"DECISION_ANNOTATE":    4,
		"DECISION_DEFER":       5,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_mcpdoll_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_mcpdoll_plugin_v1_plugin_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HostMessage_Invocation
	//	*HostMessage_Cancel
	//	*HostMessage_Shutdown
	Message       isHostMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HostMessage) GetMessage() isHostMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HostMessage) GetInvocation() *Invocation {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Invocation); ok {
			return x.Invocation
		}
	}
	return nil
}

func (x *HostMessage) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *HostMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isHostMessage_Message interface {
	isHostMessage_Message()
}

type HostMessage_Invocation struct {
	Invocation *Invocation `protobuf:"bytes,1,opt,name=invocation,proto3,oneof"`
}

type HostMessage_Cancel struct {
	// Cancellation, when the hook budget expires or the client disconnects.
	Cancel *Cancel `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type HostMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

func (*HostMessage_Invocation) isHostMessage_Message() {}

func (*HostMessage_Cancel) isHostMessage_Message() {}

func (*HostMessage_Shutdown) isHostMessage_Message() {}

type PluginMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*PluginMessage_Verdict
	//	*PluginMessage_Progress
	Message       isPluginMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginMessage) GetMessage() isPluginMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PluginMessage) GetVerdict() *Verdict {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_Verdict); ok {
			return x.Verdict
		}
	}
	return nil
}

func (x *PluginMessage) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Message.(*PluginMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isPluginMessage_Message interface {
	isPluginMessage_Message()
}

type PluginMessage_Verdict struct {
	Verdict *Verdict `protobuf:"bytes,1,opt,name=verdict,proto3,oneof"`
}

type PluginMessage_Progress struct {
	// Emitted mid-invocation for the request-trace waterfall. Advisory: the
	// host may drop these under load without affecting the verdict.
	Progress *Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

func (*PluginMessage_Verdict) isPluginMessage_Message() {}

func (*PluginMessage_Progress) isPluginMessage_Message() {}

type Invocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates the verdict with this invocation.
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Hook name, e.g. "ON_TOOL_RESULT".
	Hook string `protobuf:"bytes,2,opt,name=hook,proto3" json:"hook,omitempty"`
	// W3C trace context, so the plugin's own spans join the request's trace.
	TraceContext map[string]string `protobuf:"bytes,3,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deadline the host will enforce. The plugin should return a partial or
	// abstaining verdict before this rather than be cancelled, because a
	// cancellation is recorded as a skip and loses whatever it had computed.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// The request context the plugin is allowed to see, restricted to the
	// manifest's declared `reads` scopes. Canonical JSON.
	ContextJson string `protobuf:"bytes,5,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	// Whether this invocation is shadow-only. Passed so a plugin can cheapen its
	// work when its verdict will not be acted on — the guard, for instance, can
	// skip escalation to the larger model in shadow mode.
	Shadow        bool `protobuf:"varint,6,opt,name=shadow,proto3" json:"shadow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invocation) Reset() {
	*x = Invocation{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invocation) ProtoMessage() {}

func (x *Invocation) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invocation.ProtoReflect.Descriptor instead.
func (*Invocation) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Invocation) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Invocation) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *Invocation) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

func (x *Invocation) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Invocation) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *Invocation) GetShadow() bool {
	if x != nil {
		return x.Shadow
	}
	return false
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Cancel) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Shutdown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grace period before the host closes the stream.
	GraceMs       int32 `protobuf:"varint,1,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Shutdown) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Progress) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Verdict struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InvocationId string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Decision     Decision               `protobuf:"varint,2,opt,name=decision,proto3,enum=mcpdoll.plugin.v1.Decision" json:"decision,omitempty"`
	// Human-readable reason. Surfaced in the audit trail and, for a deny, in the
	// model-legible error the client receives.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// 0..1. Below the plugin's own threshold the host treats the verdict as
	// abstaining, which keeps a low-confidence guess from silently denying.
	Confidence float64 `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// RFC 6902 patch, canonical JSON array. Only valid for DECISION_MUTATE, and
	// only within the manifest's declared `writes` scopes.
	PatchJson string `protobuf:"bytes,5,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	// Annotations for DECISION_ANNOTATE, canonical JSON object.
	AnnotationsJson string `protobuf:"bytes,6,opt,name=annotations_json,json=annotationsJson,proto3" json:"annotations_json,omitempty"`
	// How long this verdict may be cached, keyed by the host's cache key. Zero
	// means do not cache.
	TtlMs int32 `protobuf:"varint,7,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// For DECISION_DEFER: the input the plugin needs, as an MCP InputRequest map
	// in canonical JSON.
	InputRequestsJson string `protobuf:"bytes,8,opt,name=input_requests_json,json=inputRequestsJson,proto3" json:"input_requests_json,omitempty"`
	// For DECISION_DEFER: the plugin's own opaque state, which the gateway wraps
	// in its own signed envelope before it reaches the client. The plugin never
	// sees the outer envelope.
	PluginState string `protobuf:"bytes,9,opt,name=plugin_state,json=pluginState,proto3" json:"plugin_state,omitempty"`
	// Provenance the audit record must carry. For the guard this is the pinned
	// model, prompt and policy versions — without them an audit entry cannot
	// answer "what decided this, and would it decide the same today".
	Provenance    map[string]string `protobuf:"bytes,10,rep,name=provenance,proto3" json:"provenance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Verdict) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Verdict) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *Verdict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Verdict) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Verdict) GetPatchJson() string {
	if x != nil {
		return x.PatchJson
	}
	return ""
}

func (x *Verdict) GetAnnotationsJson() string {
	if x != nil {
		return x.AnnotationsJson
	}
	return ""
}

func (x *Verdict) GetTtlMs() int32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *Verdict) GetInputRequestsJson() string {
	if x != nil {
		return x.InputRequestsJson
	}
	return ""
}

func (x *Verdict) GetPluginState() string {
	if x != nil {
		return x.PluginState
	}
	return ""
}

func (x *Verdict) GetProvenance() map[string]string {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

type DescribeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Hooks             []string               `protobuf:"bytes,3,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Reads             []string               `protobuf:"bytes,4,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes            []string               `protobuf:"bytes,5,rep,name=writes,proto3" json:"writes,omitempty"`
	IdentityDependent bool                   `protobuf:"varint,6,opt,name=identity_dependent,json=identityDependent,proto3" json:"identity_dependent,omitempty"`
	// Provenance the plugin will stamp on every verdict, declared up front so the
	// host can reject an unpinned model at load time rather than discovering it
	// in an audit record later.
	Provenance    map[string]string `protobuf:"bytes,7,rep,name=provenance,proto3" json:"provenance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpdoll_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *DescribeResponse) GetReads() []string {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *DescribeResponse) GetWrites() []string {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *DescribeResponse) GetIdentityDependent() bool {
	if x != nil {
		return x.IdentityDependent
	}
	return false
}

func (x *DescribeResponse) GetProvenance() map[string]string {
	if x != nil {
		return x.Provenance
	}
	return nil
}

var File_mcpdoll_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_mcpdoll_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1emcpdoll/plugin/v1/plugin.proto\x12\x11mcpdoll.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\vHostMessage\x12?\n" +
	"\n" +
	"invocation\x18\x01 \x01(\v2\x1d.mcpdoll.plugin.v1.InvocationH\x00R\n" +
	"invocation\x123\n" +
	"\x06cancel\x18\x02 \x01(\v2\x19.mcpdoll.plugin.v1.CancelH\x00R\x06cancel\x129\n" +
	"\bshutdown\x18\x03 \x01(\v2\x1b.mcpdoll.plugin.v1.ShutdownH\x00R\bshutdownB\t\n" +
	"\amessage\"\x8d\x01\n" +
	"\rPluginMessage\x126\n" +
	"\averdict\x18\x01 \x01(\v2\x1a.mcpdoll.plugin.v1.VerdictH\x00R\averdict\x129\n" +
	"\bprogress\x18\x02 \x01(\v2\x1b.mcpdoll.plugin.v1.ProgressH\x00R\bprogressB\t\n" +
	"\amessage\"\xcf\x02\n" +
	"\n" +
	"Invocation\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x12\n" +
	"\x04hook\x18\x02 \x01(\tR\x04hook\x12T\n" +
	"\rtrace_context\x18\x03 \x03(\v2/.mcpdoll.plugin.v1.Invocation.TraceContextEntryR\ftraceContext\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12!\n" +
	"\fcontext_json\x18\x05 \x01(\tR\vcontextJson\x12\x16\n" +
	"\x06shadow\x18\x06 \x01(\bR\x06shadow\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x06Cancel\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"%\n" +
	"\bShutdown\x12\x19\n" +
	"\bgrace_ms\x18\x01 \x01(\x05R\agraceMs\"I\n" +
	"\bProgress\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xde\x03\n" +
	"\aVerdict\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x127\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1b.mcpdoll.plugin.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"patch_json\x18\x05 \x01(\tR\tpatchJson\x12)\n" +
	"\x10annotations_json\x18\x06 \x01(\tR\x0fannotationsJson\x12\x15\n" +
	"\x06ttl_ms\x18\a \x01(\x05R\x05ttlMs\x12.\n" +
	"\x13input_requests_json\x18\b \x01(\tR\x11inputRequestsJson\x12!\n" +
	"\fplugin_state\x18\t \x01(\tR\vpluginState\x12J\n" +
	"\n" +
	"provenance\x18\n" +
	" \x03(\v2*.mcpdoll.plugin.v1.Verdict.ProvenanceEntryR\n" +
	"provenance\x1a=\n" +
	"\x0fProvenanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x11\n" +
	"\x0fDescribeRequest\"\xc7\x02\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05hooks\x18\x03 \x03(\tR\x05hooks\x12\x14\n" +
	"\x05reads\x18\x04 \x03(\tR\x05reads\x12\x16\n" +
	"\x06writes\x18\x05 \x03(\tR\x06writes\x12-\n" +
	"\x12identity_dependent\x18\x06 \x01(\bR\x11identityDependent\x12S\n" +
	"\n" +
	"provenance\x18\a \x03(\v23.mcpdoll.plugin.v1.DescribeResponse.ProvenanceEntryR\n" +
	"provenance\x1a=\n" +
	"\x0fProvenanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8b\x01\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02\x12\x13\n" +
	"\x0fDECISION_MUTATE\x10\x03\x12\x15\n" +
	"\x11DECISION_ANNOTATE\x10\x04\x12\x12\n" +
	"\x0eDECISION_DEFER\x10\x052\x80\x02\n" +
	"\n" +
	"PluginHost\x12N\n" +
	"\x06Invoke\x12\x1e.mcpdoll.plugin.v1.HostMessage\x1a .mcpdoll.plugin.v1.PluginMessage(\x010\x01\x12M\n" +
	"\x06Health\x12 .mcpdoll.plugin.v1.HealthRequest\x1a!.mcpdoll.plugin.v1.HealthResponse\x12S\n" +
	"\bDescribe\x12\".mcpdoll.plugin.v1.DescribeRequest\x1a#.mcpdoll.plugin.v1.DescribeResponseB4Z2github.com/mcpdoll/mcpdoll/internal/proto/pluginpbb\x06proto3"

var (
	file_mcpdoll_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_mcpdoll_plugin_v1_plugin_proto_rawDescData []byte
)

func file_mcpdoll_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_mcpdoll_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_mcpdoll_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpdoll_plugin_v1_plugin_proto_rawDesc), len(file_mcpdoll_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_mcpdoll_plugin_v1_plugin_proto_rawDescData
}

var file_mcpdoll_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcpdoll_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mcpdoll_plugin_v1_plugin_proto_goTypes = []any{
	(Decision)(0),                 // 0: mcpdoll.plugin.v1.Decision
	(*HostMessage)(nil),           // 1: mcpdoll.plugin.v1.HostMessage
	(*PluginMessage)(nil),         // 2: mcpdoll.plugin.v1.PluginMessage
	(*Invocation)(nil),            // 3: mcpdoll.plugin.v1.Invocation
	(*Cancel)(nil),                // 4: mcpdoll.plugin.v1.Cancel
	(*Shutdown)(nil),              // 5: mcpdoll.plugin.v1.Shutdown
	(*Progress)(nil),              // 6: mcpdoll.plugin.v1.Progress
	(*Verdict)(nil),               // 7: mcpdoll.plugin.v1.Verdict
	(*HealthRequest)(nil),         // 8: mcpdoll.plugin.v1.HealthRequest
	(*HealthResponse)(nil),        // 9: mcpdoll.plugin.v1.HealthResponse
	(*DescribeRequest)(nil),       // 10: mcpdoll.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),      // 11: mcpdoll.plugin.v1.DescribeResponse
	nil,                           // 12: mcpdoll.plugin.v1.Invocation.TraceContextEntry
	nil,                           // 13: mcpdoll.plugin.v1.Verdict.ProvenanceEntry
	nil,                           // 14: mcpdoll.plugin.v1.DescribeResponse.ProvenanceEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_mcpdoll_plugin_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: mcpdoll.plugin.v1.HostMessage.invocation:type_name -> mcpdoll.plugin.v1.Invocation
	4,  // 1: mcpdoll.plugin.v1.HostMessage.cancel:type_name -> mcpdoll.plugin.v1.Cancel
	5,  // 2: mcpdoll.plugin.v1.HostMessage.shutdown:type_name -> mcpdoll.plugin.v1.Shutdown
	7,  // 3: mcpdoll.plugin.v1.PluginMessage.verdict:type_name -> mcpdoll.plugin.v1.Verdict
	6,  // 4: mcpdoll.plugin.v1.PluginMessage.progress:type_name -> mcpdoll.plugin.v1.Progress
	12, // 5: mcpdoll.plugin.v1.Invocation.trace_context:type_name -> mcpdoll.plugin.v1.Invocation.TraceContextEntry
	15, // 6: mcpdoll.plugin.v1.Invocation.deadline:type_name -> google.protobuf.Timestamp
	0,  // 7: mcpdoll.plugin.v1.Verdict.decision:type_name -> mcpdoll.plugin.v1.Decision
	13, // 8: mcpdoll.plugin.v1.Verdict.provenance:type_name -> mcpdoll.plugin.v1.Verdict.ProvenanceEntry
	14, // 9: mcpdoll.plugin.v1.DescribeResponse.provenance:type_name -> mcpdoll.plugin.v1.DescribeResponse.ProvenanceEntry
	1,  // 10: mcpdoll.plugin.v1.PluginHost.Invoke:input_type -> mcpdoll.plugin.v1.HostMessage
	8,  // 11: mcpdoll.plugin.v1.PluginHost.Health:input_type -> mcpdoll.plugin.v1.HealthRequest
	10, // 12: mcpdoll.plugin.v1.PluginHost.Describe:input_type -> mcpdoll.plugin.v1.DescribeRequest
	2,  // 13: mcpdoll.plugin.v1.PluginHost.Invoke:output_type -> mcpdoll.plugin.v1.PluginMessage
	9,  // 14: mcpdoll.plugin.v1.PluginHost.Health:output_type -> mcpdoll.plugin.v1.HealthResponse
	11, // 15: mcpdoll.plugin.v1.PluginHost.Describe:output_type -> mcpdoll.plugin.v1.DescribeResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mcpdoll_plugin_v1_plugin_proto_init() }
func file_mcpdoll_plugin_v1_plugin_proto_init() {
	if File_mcpdoll_plugin_v1_plugin_proto != nil {
		return
	}
	file_mcpdoll_plugin_v1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*HostMessage_Invocation)(nil),
		(*HostMessage_Cancel)(nil),
		(*HostMessage_Shutdown)(nil),
	}
	file_mcpdoll_plugin_v1_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginMessage_Verdict)(nil),
		(*PluginMessage_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpdoll_plugin_v1_plugin_proto_rawDesc), len(file_mcpdoll_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcpdoll_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_mcpdoll_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_mcpdoll_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_mcpdoll_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_mcpdoll_plugin_v1_plugin_proto = out.File
	file_mcpdoll_plugin_v1_plugin_proto_goTypes = nil
	file_mcpdoll_plugin_v1_plugin_proto_depIdxs = nil
}
