// Copyright 2026 Henry Zektser.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mcpdoll/plugin/v1/plugin.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginHost_Invoke_FullMethodName   = "/mcpdoll.plugin.v1.PluginHost/Invoke"
	PluginHost_Health_FullMethodName   = "/mcpdoll.plugin.v1.PluginHost/Health"
	PluginHost_Describe_FullMethodName = "/mcpdoll.plugin.v1.PluginHost/Describe"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginHost is the contract an out-of-process gRPC plugin implements.
//
// The channel is bidirectional streaming rather than unary-per-invocation
// because the hot path cannot afford a connection setup per hook, and because a
// plugin like the LLM guard benefits from keeping model connections and caches
// warm across requests. Correlation is explicit (`invocation_id`) so the host
// can have many invocations outstanding on one stream.
type PluginHostClient interface {
	// Invoke carries hook invocations to the plugin and verdicts back. The host
	// opens one stream per plugin instance and multiplexes over it.
	Invoke(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostMessage, PluginMessage], error)
	// Health is polled by the host. A plugin that fails it is backed off and
	// restarted; its verdicts are skipped per the manifest's failure policy in
	// the meantime.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Describe lets the host verify at load time that the plugin's declared
	// hooks and scopes match the manifest it was registered with. A mismatch is a
	// load failure: the manifest is the enforced contract, so the two must agree
	// before any traffic reaches the plugin.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) Invoke(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostMessage, PluginMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginHost_ServiceDesc.Streams[0], PluginHost_Invoke_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostMessage, PluginMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_InvokeClient = grpc.BidiStreamingClient[HostMessage, PluginMessage]

func (c *pluginHostClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginHost_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginHost_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility.
//
// PluginHost is the contract an out-of-process gRPC plugin implements.
//
// The channel is bidirectional streaming rather than unary-per-invocation
// because the hot path cannot afford a connection setup per hook, and because a
// plugin like the LLM guard benefits from keeping model connections and caches
// warm across requests. Correlation is explicit (`invocation_id`) so the host
// can have many invocations outstanding on one stream.
type PluginHostServer interface {
	// Invoke carries hook invocations to the plugin and verdicts back. The host
	// opens one stream per plugin instance and multiplexes over it.
	Invoke(grpc.BidiStreamingServer[HostMessage, PluginMessage]) error
	// Health is polled by the host. A plugin that fails it is backed off and
	// restarted; its verdicts are skipped per the manifest's failure policy in
	// the meantime.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Describe lets the host verify at load time that the plugin's declared
	// hooks and scopes match the manifest it was registered with. A mismatch is a
	// load failure: the manifest is the enforced contract, so the two must agree
	// before any traffic reaches the plugin.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHostServer struct{}

func (UnimplementedPluginHostServer) Invoke(grpc.BidiStreamingServer[HostMessage, PluginMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedPluginHostServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginHostServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}
func (UnimplementedPluginHostServer) testEmbeddedByValue()                    {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	// If the following call pancis, it indicates UnimplementedPluginHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_Invoke_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginHostServer).Invoke(&grpc.GenericServerStream[HostMessage, PluginMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_InvokeServer = grpc.BidiStreamingServer[HostMessage, PluginMessage]

func _PluginHost_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcpdoll.plugin.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PluginHost_Health_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _PluginHost_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Invoke",
			Handler:       _PluginHost_Invoke_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mcpdoll/plugin/v1/plugin.proto",
}
