// Code generated by scripts/gen-routes.mjs. DO NOT EDIT.
//
// Read by tools/paritycheck to prove every API operation has a console route.
// Regenerate with `npm run routes` (or `make routes`) after editing routes.tsx.

export interface RouteBinding {
  path: string;
  operation: string;
}

export const ROUTE_BINDINGS: RouteBinding[] = [
  { path: "/login", operation: "login" },
  { path: "/logout", operation: "logout" },
  { path: "/registry", operation: "getRegistry" },
  { path: "/registry/servers", operation: "listServers" },
  { path: "/registry/servers/:serverId", operation: "getServer" },
  { path: "/registry/validate", operation: "validateRegistry" },
  { path: "/plugins", operation: "listPlugins" },
  { path: "/plugins/hooks", operation: "listHooks" },
  { path: "/snapshots", operation: "getCurrentSnapshot" },
  { path: "/snapshots/build", operation: "buildSnapshot" },
  { path: "/snapshots/inspect", operation: "inspectSnapshot" },
  { path: "/snapshots/verify", operation: "verifySnapshot" },
  { path: "/snapshots/keys", operation: "generateSigningKey" },
  { path: "/gateway", operation: "getGatewayStatus" },
  { path: "/gateway/backends", operation: "listBackends" },
  { path: "/session", operation: "getSession" },
  { path: "/gateway/revocations", operation: "getRevocations" },
  { path: "/tenants", operation: "listTenants" },
  { path: "/tenants/new", operation: "createTenant" },
  { path: "/tenants/:tenantId/delete", operation: "deleteTenant" },
  { path: "/tenants/:tenantId/users", operation: "listUsers" },
  { path: "/tenants/:tenantId/users/new", operation: "createUser" },
  { path: "/users/:userId", operation: "getUser" },
  { path: "/users/:userId/edit", operation: "updateUser" },
  { path: "/users/:userId/grants", operation: "listGrants" },
  { path: "/users/:userId/grants/edit", operation: "putGrants" },
  { path: "/users/:userId/keys", operation: "listAPIKeys" },
  { path: "/users/:userId/keys/new", operation: "mintAPIKey" },
  { path: "/users/:userId/keys/:keyId/revoke", operation: "revokeAPIKey" },
  { path: "/roles", operation: "listRoles" },
  { path: "/gateway/catalog", operation: "getCatalog" },
  { path: "/gateway/playground", operation: "callTool" },
  { path: "/system/health", operation: "getHealth" },
];
