// Code generated by scripts/gen-routes.mjs. DO NOT EDIT.
//
// Read by tools/paritycheck to prove every API operation has a console route.
// Regenerate with `npm run routes` (or `make routes`) after editing routes.tsx.

export interface RouteBinding {
  path: string;
  operation: string;
}

export const ROUTE_BINDINGS: RouteBinding[] = [
  { path: "/registry", operation: "getRegistry" },
  { path: "/registry/servers", operation: "listServers" },
  { path: "/registry/servers/:serverId", operation: "getServer" },
  { path: "/registry/validate", operation: "validateRegistry" },
  { path: "/plugins", operation: "listPlugins" },
  { path: "/plugins/hooks", operation: "listHooks" },
  { path: "/snapshots", operation: "getCurrentSnapshot" },
  { path: "/snapshots/build", operation: "buildSnapshot" },
  { path: "/snapshots/inspect", operation: "inspectSnapshot" },
  { path: "/snapshots/verify", operation: "verifySnapshot" },
  { path: "/snapshots/keys", operation: "generateSigningKey" },
  { path: "/gateway", operation: "getGatewayStatus" },
  { path: "/gateway/audiences", operation: "listAudiences" },
  { path: "/gateway/audiences/:slug/catalog", operation: "getAudienceCatalog" },
  { path: "/gateway/audiences/:slug/playground", operation: "callTool" },
  { path: "/system/health", operation: "getHealth" },
];
