// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAPIKeyGrant = `-- name: AddAPIKeyGrant :one
INSERT INTO api_key_grants (api_key_id, role, scope)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, api_key_id, role, scope
`

type AddAPIKeyGrantParams struct {
	ApiKeyID uuid.UUID
	Role     string
	Scope    string
}

func (q *Queries) AddAPIKeyGrant(ctx context.Context, arg AddAPIKeyGrantParams) (ApiKeyGrant, error) {
	row := q.db.QueryRow(ctx, addAPIKeyGrant, arg.ApiKeyID, arg.Role, arg.Scope)
	var i ApiKeyGrant
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Role,
		&i.Scope,
	)
	return i, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, tenant_id, name, prefix, hash, expires_at, spans_tenants)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants
`

type CreateAPIKeyParams struct {
	UserID       uuid.UUID
	TenantID     *uuid.UUID
	Name         string
	Prefix       string
	Hash         string
	ExpiresAt    pgtype.Timestamptz
	SpansTenants bool
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.TenantID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.ExpiresAt,
		arg.SpansTenants,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.TenantID,
		&i.SpansTenants,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.TenantID,
		&i.SpansTenants,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants FROM api_keys WHERE prefix = $1
`

// The authentication path. Looks up by the public prefix; the caller then
// verifies the secret against `hash`. Revoked and expired keys are returned
// rather than filtered, so the caller can tell "revoked" from "no such key" —
// the two deserve different log lines and the same response.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.TenantID,
		&i.SpansTenants,
	)
	return i, err
}

const listAPIKeyGrants = `-- name: ListAPIKeyGrants :many
SELECT id, api_key_id, role, scope FROM api_key_grants WHERE api_key_id = $1 ORDER BY scope, role
`

func (q *Queries) ListAPIKeyGrants(ctx context.Context, apiKeyID uuid.UUID) ([]ApiKeyGrant, error) {
	rows, err := q.db.Query(ctx, listAPIKeyGrants, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeyGrant{}
	for rows.Next() {
		var i ApiKeyGrant
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Role,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeyIDsByUser = `-- name: ListAPIKeyIDsByUser :many
SELECT id FROM api_keys WHERE user_id = $1
`

func (q *Queries) ListAPIKeyIDsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAPIKeyIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants FROM api_keys WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID *uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.TenantID,
			&i.SpansTenants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.TenantID,
			&i.SpansTenants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPIKeys = `-- name: ListActiveAPIKeys :many
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at, tenant_id, spans_tenants FROM api_keys
WHERE revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at
`

// Every key that could authenticate right now, across every tenant. This is
// what a snapshot build reads: the data plane holds no database, so the keys
// have to travel in the artifact (ADR 0021). Revoked and expired keys are
// excluded here rather than filtered later — publishing a key that cannot
// authenticate would put a dead credential's digest into a signed file for no
// reason.
func (q *Queries) ListActiveAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.TenantID,
			&i.SpansTenants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
