// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAPIKeyGrant = `-- name: AddAPIKeyGrant :one
INSERT INTO api_key_grants (api_key_id, role, scope)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, api_key_id, role, scope
`

type AddAPIKeyGrantParams struct {
	ApiKeyID uuid.UUID
	Role     string
	Scope    string
}

func (q *Queries) AddAPIKeyGrant(ctx context.Context, arg AddAPIKeyGrantParams) (ApiKeyGrant, error) {
	row := q.db.QueryRow(ctx, addAPIKeyGrant, arg.ApiKeyID, arg.Role, arg.Scope)
	var i ApiKeyGrant
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.Role,
		&i.Scope,
	)
	return i, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, prefix, hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID
	Name      string
	Prefix    string
	Hash      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at FROM api_keys WHERE prefix = $1
`

// The authentication path. Looks up by the public prefix; the caller then
// verifies the secret against `hash`. Revoked and expired keys are returned
// rather than filtered, so the caller can tell "revoked" from "no such key" —
// the two deserve different log lines and the same response.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeyGrants = `-- name: ListAPIKeyGrants :many
SELECT id, api_key_id, role, scope FROM api_key_grants WHERE api_key_id = $1 ORDER BY scope, role
`

func (q *Queries) ListAPIKeyGrants(ctx context.Context, apiKeyID uuid.UUID) ([]ApiKeyGrant, error) {
	rows, err := q.db.Query(ctx, listAPIKeyGrants, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeyGrant{}
	for rows.Next() {
		var i ApiKeyGrant
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Role,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT k.id, k.user_id, k.name, k.prefix, k.hash, k.created_at, k.last_used_at, k.expires_at, k.revoked_at FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE u.tenant_id = $1
ORDER BY k.created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, prefix, hash, created_at, last_used_at, expires_at, revoked_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
