// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAPIKeyGrant(ctx context.Context, arg AddAPIKeyGrantParams) (ApiKeyGrant, error)
	AddRevocation(ctx context.Context, arg AddRevocationParams) (Revocation, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	// The principal set's version. Monotonic, and what the data plane compares
	// against what it holds — a set that did not bump would publish a file nobody
	// applies.
	BumpPrincipalVersion(ctx context.Context) (RevocationState, error)
	// Monotonic, and the version the data plane compares against what it holds.
	BumpRevocationVersion(ctx context.Context) (RevocationState, error)
	// Atomically take one due schedule and push its next run out.
	//
	// The `next_run_at <= now()` in the WHERE clause is what makes this safe with
	// more than one control-plane replica: the row lock serializes the update, and
	// the loser's WHERE no longer matches, so it claims nothing. Ragdoll's
	// scheduler documented the opposite — listDue then markRun, unfenced, with a
	// note that two instances double-fire and would need leader election. Claiming
	// in the UPDATE costs nothing and removes that whole class of problem.
	ClaimDueSchedule(ctx context.Context, arg ClaimDueScheduleParams) (Schedule, error)
	// CountUsersByTenant answers the tenant list in one query rather than one per
	// tenant. A tenant list is the first screen an operator opens, and N+1 there is
	// N+1 forever.
	// Counted from grants, since a user no longer belongs to a tenant. A grant at
	// global scope reaches every tenant and is counted for each.
	CountUsersByTenant(ctx context.Context) ([]CountUsersByTenantRow, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error)
	CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// No tenant: a user is a person, and which tenants they reach is what their
	// grants say (ADR 0014, amended). A user with no grants is inert, which is why
	// creating one is safe at any scope.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	// Rows whose credential could not authenticate anyway. Kept for a grace period
	// so a session that expired an hour ago still explains itself in an audit.
	DeleteExpiredSessions(ctx context.Context) error
	// Grants name a scope as text, not a tenant by foreign key, so nothing cascades
	// when a tenant is deleted. Left behind they are dormant *and* dangerous: a
	// tenant recreated with the same slug would silently re-authorize everyone who
	// was granted into the old one.
	DeleteGrantsInTenant(ctx context.Context, scope string) error
	DeleteIdentityProvider(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, role string) error
	// The slug is deliberately absent from UpdateTenant: it appears in every scope
	// string, so renaming a tenant would orphan every grant naming it.
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Bring a schedule forward so the next tick takes it. "Run now" without a
	// second execution path: the same loop, the same claim, the same outcome
	// recording. A separate synchronous run would be a second way for a job to
	// happen, and the two would drift.
	DueNow(ctx context.Context, jobType string) error
	GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	// The authentication path. Looks up by the public prefix; the caller then
	// verifies the secret against `hash`. Revoked and expired keys are returned
	// rather than filtered, so the caller can tell "revoked" from "no such key" —
	// the two deserve different log lines and the same response.
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetAuthSettings(ctx context.Context) (AuthSetting, error)
	GetIdentityProviderBySlug(ctx context.Context, slug string) (IdentityProvider, error)
	GetRevocationState(ctx context.Context) (RevocationState, error)
	GetScheduleByJobType(ctx context.Context, jobType string) (Schedule, error)
	// The authentication path. Looks up by the public prefix; the caller verifies
	// the secret against `hash`. Revoked and expired rows are returned rather than
	// filtered, so the caller can tell "expired" from "no such session" — the two
	// deserve different log lines and the same response.
	GetSessionByPrefix(ctx context.Context, prefix string) (Session, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	// Globally unique, so signing in needs an email and a password and nothing
	// else.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error)
	LinkIdentity(ctx context.Context, arg LinkIdentityParams) (UserIdentity, error)
	ListAPIKeyGrants(ctx context.Context, apiKeyID uuid.UUID) ([]ApiKeyGrant, error)
	ListAPIKeyIDsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID *uuid.UUID) ([]ApiKey, error)
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	// Every key that could authenticate right now, across every tenant. This is
	// what a snapshot build reads: the data plane holds no database, so the keys
	// have to travel in the artifact (ADR 0021). Revoked and expired keys are
	// excluded here rather than filtered later — publishing a key that cannot
	// authenticate would put a dead credential's digest into a signed file for no
	// reason.
	ListActiveAPIKeys(ctx context.Context) ([]ApiKey, error)
	// Everything the data plane must still refuse. A superseded entry is one a
	// published snapshot already omits, so carrying it would only make the signed
	// list bigger.
	ListActiveRevocations(ctx context.Context) ([]Revocation, error)
	ListAllAPIKeyGrants(ctx context.Context) ([]ApiKeyGrant, error)
	// Every user's grants in one query. A snapshot build needs all of them, and
	// asking per user turns a publish into one round trip per person on staff.
	ListAllGrants(ctx context.Context) ([]Grant, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	// The login screen's list. A tenant-scoped provider (tenant_id set) is offered
	// only to that tenant; a null tenant_id serves every tenant.
	ListEnabledIdentityProviders(ctx context.Context, tenantID *uuid.UUID) ([]IdentityProvider, error)
	// Grants *within* a tenant's scope, which is now the only sense in which a
	// grant belongs to a tenant.
	ListGrantsByTenant(ctx context.Context, scope string) ([]Grant, error)
	ListGrantsByUser(ctx context.Context, userID uuid.UUID) ([]Grant, error)
	ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error)
	ListIdentityProviders(ctx context.Context) ([]IdentityProvider, error)
	ListRolePermissions(ctx context.Context) ([]RolePermission, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	// Users *granted into* a tenant rather than owned by one. A more useful
	// listing than ownership was: it answers "who can reach this tenant", which is
	// the question an administrator is actually asking.
	ListUsersInTenant(ctx context.Context, scope string) ([]User, error)
	RecordScheduleOutcome(ctx context.Context, arg RecordScheduleOutcomeParams) error
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	RevokeGrant(ctx context.Context, arg RevokeGrantParams) error
	RevokeGrantByID(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// Signing somebody out everywhere. Returns the ids so each becomes a revocation
	// entry: a session already handed out is a live credential, and marking the row
	// is not the same as stopping it.
	RevokeSessionsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	SetRevocationPrunedThrough(ctx context.Context, prunedThrough int64) (RevocationState, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// Called when a snapshot is published: every revocation committed before the
	// build read the database is already reflected in it.
	SupersedeRevocationsBefore(ctx context.Context, arg SupersedeRevocationsBeforeParams) error
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UnlinkIdentity(ctx context.Context, id uuid.UUID) error
	UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error)
	UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (IdentityProvider, error)
	UpdateScheduleCadence(ctx context.Context, arg UpdateScheduleCadenceParams) (Schedule, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Registration, run at startup for every job the binary knows how to do.
	//
	// The cadence is NOT overwritten on conflict. A schedule an operator has
	// retuned or disabled must survive a restart — otherwise every deploy silently
	// reverts their decision, which is worse than not letting them make it.
	UpsertSystemSchedule(ctx context.Context, arg UpsertSystemScheduleParams) (Schedule, error)
}

var _ Querier = (*Queries)(nil)
