// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAPIKeyGrant(ctx context.Context, arg AddAPIKeyGrantParams) (ApiKeyGrant, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	// CountUsersByTenant answers the tenant list in one query rather than one per
	// tenant. A tenant list is the first screen an operator opens, and N+1 there is
	// N+1 forever.
	CountUsersByTenant(ctx context.Context) ([]CountUsersByTenantRow, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error)
	CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteIdentityProvider(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, role string) error
	// The slug is deliberately absent from UpdateTenant: it appears in every scope
	// string, so renaming a tenant would orphan every grant naming it.
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// The authentication path. Looks up by the public prefix; the caller then
	// verifies the secret against `hash`. Revoked and expired keys are returned
	// rather than filtered, so the caller can tell "revoked" from "no such key" —
	// the two deserve different log lines and the same response.
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetAuthSettings(ctx context.Context) (AuthSetting, error)
	GetIdentityProviderBySlug(ctx context.Context, slug string) (IdentityProvider, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error)
	LinkIdentity(ctx context.Context, arg LinkIdentityParams) (UserIdentity, error)
	ListAPIKeyGrants(ctx context.Context, apiKeyID uuid.UUID) ([]ApiKeyGrant, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error)
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	// The login screen's list. A tenant-scoped provider (tenant_id set) is offered
	// only to that tenant; a null tenant_id serves every tenant.
	ListEnabledIdentityProviders(ctx context.Context, tenantID *uuid.UUID) ([]IdentityProvider, error)
	ListGrantsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Grant, error)
	ListGrantsByUser(ctx context.Context, userID uuid.UUID) ([]Grant, error)
	ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error)
	ListIdentityProviders(ctx context.Context) ([]IdentityProvider, error)
	ListRolePermissions(ctx context.Context) ([]RolePermission, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	RevokeGrant(ctx context.Context, arg RevokeGrantParams) error
	RevokeGrantByID(ctx context.Context, id uuid.UUID) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UnlinkIdentity(ctx context.Context, id uuid.UUID) error
	UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error)
	UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (IdentityProvider, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
