// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role, permission)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	Role       string
	Permission string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.Role, arg.Permission)
	return err
}

const bumpPrincipalVersion = `-- name: BumpPrincipalVersion :one
UPDATE revocation_state
SET principal_version = principal_version + 1, updated_at = now()
WHERE id = true
RETURNING id, version, pruned_through, updated_at, principal_version
`

// The principal set's version. Monotonic, and what the data plane compares
// against what it holds — a set that did not bump would publish a file nobody
// applies.
func (q *Queries) BumpPrincipalVersion(ctx context.Context) (RevocationState, error) {
	row := q.db.QueryRow(ctx, bumpPrincipalVersion)
	var i RevocationState
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.PrunedThrough,
		&i.UpdatedAt,
		&i.PrincipalVersion,
	)
	return i, err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO grants (user_id, role, scope, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, role, scope) DO UPDATE
  SET granted_by = EXCLUDED.granted_by
RETURNING id, user_id, role, scope, granted_by, created_at
`

type CreateGrantParams struct {
	UserID    uuid.UUID
	Role      string
	Scope     string
	GrantedBy *uuid.UUID
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.UserID,
		arg.Role,
		arg.Scope,
		arg.GrantedBy,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Scope,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGrantsInTenant = `-- name: DeleteGrantsInTenant :exec
DELETE FROM grants WHERE scope = $1 OR scope LIKE $1 || '/%'
`

// Grants name a scope as text, not a tenant by foreign key, so nothing cascades
// when a tenant is deleted. Left behind they are dormant *and* dangerous: a
// tenant recreated with the same slug would silently re-authorize everyone who
// was granted into the old one.
func (q *Queries) DeleteGrantsInTenant(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, deleteGrantsInTenant, scope)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM role_permissions WHERE role = $1
`

func (q *Queries) DeleteRole(ctx context.Context, role string) error {
	_, err := q.db.Exec(ctx, deleteRole, role)
	return err
}

const listAllAPIKeyGrants = `-- name: ListAllAPIKeyGrants :many
SELECT id, api_key_id, role, scope FROM api_key_grants ORDER BY api_key_id, scope, role
`

func (q *Queries) ListAllAPIKeyGrants(ctx context.Context) ([]ApiKeyGrant, error) {
	rows, err := q.db.Query(ctx, listAllAPIKeyGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeyGrant{}
	for rows.Next() {
		var i ApiKeyGrant
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Role,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGrants = `-- name: ListAllGrants :many
SELECT id, user_id, role, scope, granted_by, created_at FROM grants ORDER BY user_id, scope, role
`

// Every user's grants in one query. A snapshot build needs all of them, and
// asking per user turns a publish into one round trip per person on staff.
func (q *Queries) ListAllGrants(ctx context.Context) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listAllGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Scope,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByTenant = `-- name: ListGrantsByTenant :many
SELECT id, user_id, role, scope, granted_by, created_at FROM grants
WHERE scope = $1 OR scope LIKE $1 || '/%'
ORDER BY user_id, scope, role
`

// Grants *within* a tenant's scope, which is now the only sense in which a
// grant belongs to a tenant.
func (q *Queries) ListGrantsByTenant(ctx context.Context, scope string) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listGrantsByTenant, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Scope,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByUser = `-- name: ListGrantsByUser :many
SELECT id, user_id, role, scope, granted_by, created_at FROM grants WHERE user_id = $1 ORDER BY scope, role
`

func (q *Queries) ListGrantsByUser(ctx context.Context, userID uuid.UUID) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listGrantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Scope,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT role, permission FROM role_permissions ORDER BY role, permission
`

func (q *Queries) ListRolePermissions(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.Role, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions WHERE role = $1 AND permission = $2
`

type RemoveRolePermissionParams struct {
	Role       string
	Permission string
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.Role, arg.Permission)
	return err
}

const revokeGrant = `-- name: RevokeGrant :exec
DELETE FROM grants WHERE user_id = $1 AND role = $2 AND scope = $3
`

type RevokeGrantParams struct {
	UserID uuid.UUID
	Role   string
	Scope  string
}

func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) error {
	_, err := q.db.Exec(ctx, revokeGrant, arg.UserID, arg.Role, arg.Scope)
	return err
}

const revokeGrantByID = `-- name: RevokeGrantByID :exec
DELETE FROM grants WHERE id = $1
`

func (q *Queries) RevokeGrantByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeGrantByID, id)
	return err
}
