// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRevocation = `-- name: AddRevocation :one
INSERT INTO revocations (principal_id, kind, user_id, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (principal_id) DO UPDATE SET revoked_at = now(), reason = EXCLUDED.reason
RETURNING id, principal_id, kind, user_id, reason, revoked_at, superseded_by
`

type AddRevocationParams struct {
	PrincipalID uuid.UUID
	Kind        string
	UserID      *uuid.UUID
	Reason      *string
}

func (q *Queries) AddRevocation(ctx context.Context, arg AddRevocationParams) (Revocation, error) {
	row := q.db.QueryRow(ctx, addRevocation,
		arg.PrincipalID,
		arg.Kind,
		arg.UserID,
		arg.Reason,
	)
	var i Revocation
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Kind,
		&i.UserID,
		&i.Reason,
		&i.RevokedAt,
		&i.SupersededBy,
	)
	return i, err
}

const bumpRevocationVersion = `-- name: BumpRevocationVersion :one
UPDATE revocation_state
SET version = version + 1, updated_at = now()
WHERE id = true
RETURNING id, version, pruned_through, updated_at
`

// Monotonic, and the version the data plane compares against what it holds.
func (q *Queries) BumpRevocationVersion(ctx context.Context) (RevocationState, error) {
	row := q.db.QueryRow(ctx, bumpRevocationVersion)
	var i RevocationState
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.PrunedThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevocationState = `-- name: GetRevocationState :one
SELECT id, version, pruned_through, updated_at FROM revocation_state WHERE id = true
`

func (q *Queries) GetRevocationState(ctx context.Context) (RevocationState, error) {
	row := q.db.QueryRow(ctx, getRevocationState)
	var i RevocationState
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.PrunedThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRevocations = `-- name: ListActiveRevocations :many
SELECT id, principal_id, kind, user_id, reason, revoked_at, superseded_by FROM revocations WHERE superseded_by IS NULL ORDER BY id
`

// Everything the data plane must still refuse. A superseded entry is one a
// published snapshot already omits, so carrying it would only make the signed
// list bigger.
func (q *Queries) ListActiveRevocations(ctx context.Context) ([]Revocation, error) {
	rows, err := q.db.Query(ctx, listActiveRevocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revocation{}
	for rows.Next() {
		var i Revocation
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.Kind,
			&i.UserID,
			&i.Reason,
			&i.RevokedAt,
			&i.SupersededBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRevocationPrunedThrough = `-- name: SetRevocationPrunedThrough :one
UPDATE revocation_state
SET version = version + 1, pruned_through = $1, updated_at = now()
WHERE id = true
RETURNING id, version, pruned_through, updated_at
`

func (q *Queries) SetRevocationPrunedThrough(ctx context.Context, prunedThrough int64) (RevocationState, error) {
	row := q.db.QueryRow(ctx, setRevocationPrunedThrough, prunedThrough)
	var i RevocationState
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.PrunedThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeRevocationsBefore = `-- name: SupersedeRevocationsBefore :exec
UPDATE revocations
SET superseded_by = $1
WHERE superseded_by IS NULL AND revoked_at < $2
`

type SupersedeRevocationsBeforeParams struct {
	SupersededBy *int64
	RevokedAt    pgtype.Timestamptz
}

// Called when a snapshot is published: every revocation committed before the
// build read the database is already reflected in it.
func (q *Queries) SupersedeRevocationsBefore(ctx context.Context, arg SupersedeRevocationsBeforeParams) error {
	_, err := q.db.Exec(ctx, supersedeRevocationsBefore, arg.SupersededBy, arg.RevokedAt)
	return err
}
