// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueSchedule = `-- name: ClaimDueSchedule :one
UPDATE schedules s
SET next_run_at = now() + $2::interval, last_run_at = now(), updated_at = now()
WHERE s.id = (
  SELECT d.id FROM schedules d
  WHERE d.enabled AND d.next_run_at IS NOT NULL AND d.next_run_at <= now()
    AND d.job_type = $1
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, job_type, name, kind, spec, enabled, system, next_run_at, last_run_at, last_error, last_duration_ms, created_at, updated_at
`

type ClaimDueScheduleParams struct {
	JobType string
	Column2 pgtype.Interval
}

// Atomically take one due schedule and push its next run out.
//
// The `next_run_at <= now()` in the WHERE clause is what makes this safe with
// more than one control-plane replica: the row lock serializes the update, and
// the loser's WHERE no longer matches, so it claims nothing. Ragdoll's
// scheduler documented the opposite — listDue then markRun, unfenced, with a
// note that two instances double-fire and would need leader election. Claiming
// in the UPDATE costs nothing and removes that whole class of problem.
func (q *Queries) ClaimDueSchedule(ctx context.Context, arg ClaimDueScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, claimDueSchedule, arg.JobType, arg.Column2)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Enabled,
		&i.System,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
		&i.LastDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dueNow = `-- name: DueNow :exec
UPDATE schedules SET next_run_at = now(), updated_at = now() WHERE job_type = $1
`

// Bring a schedule forward so the next tick takes it. "Run now" without a
// second execution path: the same loop, the same claim, the same outcome
// recording. A separate synchronous run would be a second way for a job to
// happen, and the two would drift.
func (q *Queries) DueNow(ctx context.Context, jobType string) error {
	_, err := q.db.Exec(ctx, dueNow, jobType)
	return err
}

const getScheduleByJobType = `-- name: GetScheduleByJobType :one
SELECT id, job_type, name, kind, spec, enabled, system, next_run_at, last_run_at, last_error, last_duration_ms, created_at, updated_at FROM schedules WHERE job_type = $1
`

func (q *Queries) GetScheduleByJobType(ctx context.Context, jobType string) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByJobType, jobType)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Enabled,
		&i.System,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
		&i.LastDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, job_type, name, kind, spec, enabled, system, next_run_at, last_run_at, last_error, last_duration_ms, created_at, updated_at FROM schedules ORDER BY name
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Name,
			&i.Kind,
			&i.Spec,
			&i.Enabled,
			&i.System,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastError,
			&i.LastDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleOutcome = `-- name: RecordScheduleOutcome :exec
UPDATE schedules
SET last_error = $2, last_duration_ms = $3, updated_at = now()
WHERE id = $1
`

type RecordScheduleOutcomeParams struct {
	ID             uuid.UUID
	LastError      *string
	LastDurationMs *int32
}

func (q *Queries) RecordScheduleOutcome(ctx context.Context, arg RecordScheduleOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordScheduleOutcome, arg.ID, arg.LastError, arg.LastDurationMs)
	return err
}

const updateScheduleCadence = `-- name: UpdateScheduleCadence :one
UPDATE schedules
SET spec = COALESCE($2, spec),
    enabled = COALESCE($3, enabled),
    -- Re-arm from now. Without this, lengthening a cadence leaves the old
    -- next_run_at in place and the change appears not to have taken; and
    -- re-enabling a schedule whose next_run_at is years stale would fire it
    -- immediately and then keep firing to catch up.
    next_run_at = now(),
    updated_at = now()
WHERE job_type = $1
RETURNING id, job_type, name, kind, spec, enabled, system, next_run_at, last_run_at, last_error, last_duration_ms, created_at, updated_at
`

type UpdateScheduleCadenceParams struct {
	JobType string
	Spec    *string
	Enabled *bool
}

func (q *Queries) UpdateScheduleCadence(ctx context.Context, arg UpdateScheduleCadenceParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateScheduleCadence, arg.JobType, arg.Spec, arg.Enabled)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Enabled,
		&i.System,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
		&i.LastDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSchedule = `-- name: UpsertSystemSchedule :one
INSERT INTO schedules (job_type, name, kind, spec, system, next_run_at)
VALUES ($1, $2, $3, $4, true, now())
ON CONFLICT (job_type) DO UPDATE
  SET name = EXCLUDED.name, updated_at = now()
RETURNING id, job_type, name, kind, spec, enabled, system, next_run_at, last_run_at, last_error, last_duration_ms, created_at, updated_at
`

type UpsertSystemScheduleParams struct {
	JobType string
	Name    string
	Kind    string
	Spec    string
}

// Registration, run at startup for every job the binary knows how to do.
//
// The cadence is NOT overwritten on conflict. A schedule an operator has
// retuned or disabled must survive a restart — otherwise every deploy silently
// reverts their decision, which is worse than not letting them make it.
func (q *Queries) UpsertSystemSchedule(ctx context.Context, arg UpsertSystemScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, upsertSystemSchedule,
		arg.JobType,
		arg.Name,
		arg.Kind,
		arg.Spec,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Enabled,
		&i.System,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
		&i.LastDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
