// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createIdentityProvider = `-- name: CreateIdentityProvider :one
INSERT INTO identity_providers (slug, kind, display_name, enabled, tenant_id, config)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, kind, display_name, enabled, tenant_id, config, created_at, updated_at
`

type CreateIdentityProviderParams struct {
	Slug        string
	Kind        string
	DisplayName string
	Enabled     bool
	TenantID    *uuid.UUID
	Config      []byte
}

func (q *Queries) CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, createIdentityProvider,
		arg.Slug,
		arg.Kind,
		arg.DisplayName,
		arg.Enabled,
		arg.TenantID,
		arg.Config,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.TenantID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdentityProvider = `-- name: DeleteIdentityProvider :exec
DELETE FROM identity_providers WHERE id = $1
`

func (q *Queries) DeleteIdentityProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdentityProvider, id)
	return err
}

const getAuthSettings = `-- name: GetAuthSettings :one
SELECT id, signup_mode, default_role, updated_at FROM auth_settings WHERE id = true
`

func (q *Queries) GetAuthSettings(ctx context.Context) (AuthSetting, error) {
	row := q.db.QueryRow(ctx, getAuthSettings)
	var i AuthSetting
	err := row.Scan(
		&i.ID,
		&i.SignupMode,
		&i.DefaultRole,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityProviderBySlug = `-- name: GetIdentityProviderBySlug :one
SELECT id, slug, kind, display_name, enabled, tenant_id, config, created_at, updated_at FROM identity_providers WHERE slug = $1
`

func (q *Queries) GetIdentityProviderBySlug(ctx context.Context, slug string) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, getIdentityProviderBySlug, slug)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.TenantID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledIdentityProviders = `-- name: ListEnabledIdentityProviders :many
SELECT id, slug, kind, display_name, enabled, tenant_id, config, created_at, updated_at FROM identity_providers
WHERE enabled = true AND (tenant_id IS NULL OR tenant_id = $1)
ORDER BY display_name
`

// The login screen's list. A tenant-scoped provider (tenant_id set) is offered
// only to that tenant; a null tenant_id serves every tenant.
func (q *Queries) ListEnabledIdentityProviders(ctx context.Context, tenantID *uuid.UUID) ([]IdentityProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledIdentityProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.DisplayName,
			&i.Enabled,
			&i.TenantID,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT id, slug, kind, display_name, enabled, tenant_id, config, created_at, updated_at FROM identity_providers ORDER BY slug
`

func (q *Queries) ListIdentityProviders(ctx context.Context) ([]IdentityProvider, error) {
	rows, err := q.db.Query(ctx, listIdentityProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.DisplayName,
			&i.Enabled,
			&i.TenantID,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthSettings = `-- name: UpdateAuthSettings :one
UPDATE auth_settings
SET signup_mode = $1, default_role = $2, updated_at = now()
WHERE id = true
RETURNING id, signup_mode, default_role, updated_at
`

type UpdateAuthSettingsParams struct {
	SignupMode  string
	DefaultRole *string
}

func (q *Queries) UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error) {
	row := q.db.QueryRow(ctx, updateAuthSettings, arg.SignupMode, arg.DefaultRole)
	var i AuthSetting
	err := row.Scan(
		&i.ID,
		&i.SignupMode,
		&i.DefaultRole,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityProvider = `-- name: UpdateIdentityProvider :one
UPDATE identity_providers
SET kind = $2, display_name = $3, enabled = $4, config = $5, updated_at = now()
WHERE id = $1
RETURNING id, slug, kind, display_name, enabled, tenant_id, config, created_at, updated_at
`

type UpdateIdentityProviderParams struct {
	ID          uuid.UUID
	Kind        string
	DisplayName string
	Enabled     bool
	Config      []byte
}

func (q *Queries) UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, updateIdentityProvider,
		arg.ID,
		arg.Kind,
		arg.DisplayName,
		arg.Enabled,
		arg.Config,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.TenantID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
