// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, display_name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, display_name, password_hash, status, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID
	Email        string
	DisplayName  *string
	PasswordHash *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, display_name, password_hash, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, display_name, password_hash, status, created_at, updated_at FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID
	Email    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.tenant_id, u.email, u.display_name, u.password_hash, u.status, u.created_at, u.updated_at FROM users u
JOIN user_identities i ON i.user_id = u.id
WHERE i.provider = $1 AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkIdentity = `-- name: LinkIdentity :one
INSERT INTO user_identities (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, email, created_at
`

type LinkIdentityParams struct {
	UserID   uuid.UUID
	Provider string
	Subject  string
	Email    *string
}

func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, linkIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, tenant_id, email, display_name, password_hash, status, created_at, updated_at FROM users ORDER BY tenant_id, email
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, subject, email, created_at FROM user_identities WHERE user_id = $1 ORDER BY provider
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, email, display_name, password_hash, status, created_at, updated_at FROM users WHERE tenant_id = $1 ORDER BY email
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const unlinkIdentity = `-- name: UnlinkIdentity :exec
DELETE FROM user_identities WHERE id = $1
`

func (q *Queries) UnlinkIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkIdentity, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, email, display_name, password_hash, status, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	DisplayName *string
	Status      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
