// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countUsersByTenant = `-- name: CountUsersByTenant :many
SELECT t.id AS tenant_id, count(DISTINCT g.user_id)::bigint AS users
FROM tenants t
LEFT JOIN grants g
  ON g.scope = 't/' || t.slug
  OR g.scope LIKE 't/' || t.slug || '/%'
  OR g.scope = '*'
GROUP BY t.id
`

type CountUsersByTenantRow struct {
	TenantID uuid.UUID
	Users    int64
}

// CountUsersByTenant answers the tenant list in one query rather than one per
// tenant. A tenant list is the first screen an operator opens, and N+1 there is
// N+1 forever.
// Counted from grants, since a user no longer belongs to a tenant. A grant at
// global scope reaches every tenant and is counted for each.
func (q *Queries) CountUsersByTenant(ctx context.Context) ([]CountUsersByTenantRow, error) {
	rows, err := q.db.Query(ctx, countUsersByTenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersByTenantRow{}
	for rows.Next() {
		var i CountUsersByTenantRow
		if err := rows.Scan(&i.TenantID, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, password_hash, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	DisplayName  *string
	PasswordHash *string
}

// No tenant: a user is a person, and which tenants they reach is what their
// grants say (ADR 0014, amended). A user with no grants is inert, which is why
// creating one is safe at any scope.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, password_hash, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, status, created_at, updated_at FROM users WHERE email = $1
`

// Globally unique, so signing in needs an email and a password and nothing
// else.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.email, u.display_name, u.password_hash, u.status, u.created_at, u.updated_at FROM users u
JOIN user_identities i ON i.user_id = u.id
WHERE i.provider = $1 AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkIdentity = `-- name: LinkIdentity :one
INSERT INTO user_identities (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, email, created_at
`

type LinkIdentityParams struct {
	UserID   uuid.UUID
	Provider string
	Subject  string
	Email    *string
}

func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, linkIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, display_name, password_hash, status, created_at, updated_at FROM users ORDER BY email
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, user_id, provider, subject, email, created_at FROM user_identities WHERE user_id = $1 ORDER BY provider
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInTenant = `-- name: ListUsersInTenant :many
SELECT DISTINCT u.id, u.email, u.display_name, u.password_hash, u.status, u.created_at, u.updated_at FROM users u
JOIN grants g ON g.user_id = u.id
WHERE g.scope = $1 OR g.scope LIKE $1 || '/%' OR g.scope = '*'
ORDER BY u.email
`

// Users *granted into* a tenant rather than owned by one. A more useful
// listing than ownership was: it answers "who can reach this tenant", which is
// the question an administrator is actually asking.
func (q *Queries) ListUsersInTenant(ctx context.Context, scope string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersInTenant, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const unlinkIdentity = `-- name: UnlinkIdentity :exec
DELETE FROM user_identities WHERE id = $1
`

func (q *Queries) UnlinkIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkIdentity, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, password_hash, status, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	DisplayName *string
	Status      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
